const fs = require("fs");

const dummytext = `SemioticspolaroidgochujangutnisiviraltildevaporwareyesplzunicornincididuntascotjeanshortsjianbingMarfamukbangbruhetnarwhalIrureuthoodiealiquipcloudbreadwokegatekeepadipisicingcupidatatascotaliquaHoodiecloudbreadhellaicelanddoBiodieselkalechipshellaveniamdolorXOXOtonxmollitsemioticsUtsunteiusmodbutcheridintonxminimAffogatounicorncoppermugneutraDIYconsequateiusmodpalosantopokpokTweeaffogatowayfarersracletteirureullamcoDIYmehmigassingle-origincoffeeLive-edgekickstarteriPhonemukbangmeggingsfourlokotumblrroofpartyfammeditationtbhbutcherMinimsingle-origincoffeetbhdeepvGastropubglossierbodegaboysflexitarianYOLOHellakinfolkunicornascotveniamnullaClichevexillologistselvageflexitariancillumcommodoramps+1susUghoffalfourlokoreprehenderitsamehoodieLive-edgeplaidwilliamsburgjeanshortsSchlitzscenestersquidmumblecorepinterestkeffiyehtacospitchforktotebagmlkshknarwhalloremvexillologistyrthundercatsWayfarershammockforagetumericrampspickled90'sfingerstachetweetypewriterfourdollartoastthundercatsdistilleryrawdenimAsymmetricalautesingle-origincoffeestumptownduisGlossierdolorsintneutraplaidviralnostrudVibecessionvaporware8-bitpickledlaborumafsartorialsubwaytilecillumconsequatGochujangbeardascotviceinsuslaborumvaporwarecornholefugiatbluebottleVHSSalviatrustfundlisticleorganicmixtapelacroixbluebottlebittersdolorpariaturLumbersexualdoloreveganchiaRoofpartyethicalnostrudartisanVHSCulpamigasmlkshkviraleverydaycarrydolorebittersraclettereprehenderitwilliamsburg8-bitpickledactuallychurch-keyscenesterfreeganhoodieDolorepop-upmeggingsanimChambraycloudbreadlisticlesquidIntelligentsialive-edgeiruretrustfundquiphotoboothpoutinelaborumJeanshortsmanbunexcepteurfoodtruckmessengerbagethicaladOrganicsedwolfXOXO+1greenjuicevicesrirachaipsumCupidatatasymmetricalreprehenderitsustainableoccaecatvibecessionKickstartersnackwavedreamcatcherkalechipschambraygodardsemioticslacroixirurestreetartflannelbluebottleyuccieCoppermugughbushwickduisirurehellofechoparkleggingsbutcherStreetartincididuntsintfannypackkogimumblecoreFamchurch-keyenimdeseruntlyftsartorialchillwaveinaliquiplacroixjianbingadaptogenkeffiyehGluten-freevelitidgodardTacosconsecteturdirecttradepickledbiodieseltemporwilliamsburgoffalautereadymadeascotcronutaestheticcillumrampsPalosantohumblebragcrucifixchicharronesswagadipisicingtumericwaistcoatexercitationchiaYOLOFannypackcloudbreadshamanadaptogenwokepaleoproidentYOLOsusporkbellysartorialOfficiacold-pressedwilliamsburgmastercleansedeepvfourlokomeggingstaiyakicardiganlo-fipaleobiodieselgastropubfixieTotebageverydaycarryconsecteturcraygastropubsartorialmanbunasymmetricalfiteukeytarchillwavefranzenkitschEtelitseitanmeggingsvoluptatevaporwarefixieblogtruffautbiodieselforageeatotebagPinterestvaporwareplaidexrawdenimculpapitchforkkombuchaorganicnostrudipsumfashionaxePokewolfhumblebragaffogatoiPhonebespoke3wolfmoonCold-pressedsingle-origincoffeeinsquidkinfolkLumbersexualwilliamsburgsingle-origincoffeewayfarersmehsrirachadrinkingvinegarSmallbatchdoloremustachereadymadeTattooedtildeduisenimminimwolfsustainablereprehenderitTweepolaroidyesplzsalviafranzentotebaglaborisviralmeggingsquinoaEsseYOLOkeytarwolfvaporwarecraysemioticspariaturfingerstachebodegaboysauteIrureesselaborumintildeprismslow-carbOfficiagatekeephashtagdrinkingvinegarlacroixjianbingsynthlive-edgeDIYipsumhelveticaNullakombuchaneutramanbunjeanshortsetBrooklynLocavorevelitvexillologist8-bittrustfundartpartyennuibluebottlemeggingshealthgothmigasenamelpincillumEtbitterstaiyakiblogsubwaytileheirloomLoremmanbunkombuchalaborumbodegaboyspariaturMlkshkwayfarersfoodtruck+1gastropubpinterestXOXOsalviaTweelomochillwaveullamcohelloffamsussintXOXOtumericdoBicyclerightsselvagelumbersexualXOXOknausgaardmumblecorewokedirecttradekinfolkfit8-bitBrooklyntemporcrayFlexitarianaffogatoseddolyftletterpresschambraychurch-keyEdisonbulbpitchforkforageheirloomdrinkingvinegarpraxisbittersbeardmehsedEnamelpinroofpartyflanneloccupybanhmiutasymmetricalofficialaboretemporexcepteurchambraypolaroidmukbangCulpaDSAvenmomigasautelocavorevoluptatenostrudfourlokosquidNontemporveganiPhonenostrudchiatruffautknausgaardNarwhalaestheticunicorncornholevoluptateactuallygluten-freeanimchurch-keyiruregatekeepsustainablepariaturTemporiPhoneeiusmodleggingsennuietsyporkbelly8-bitpour-overidyouprobablyhaven'theardofthemdirecttrademumblecorebeforetheysoldouttacosEtcraytweeDIYCardiganskateboardnisiloremlo-fiactivatedcharcoalpaleo3wolfmoonpinteresteastumptownadPBR&BfoodtruckOfficialisticlelo-ficlicheinirurehealthgothpop-updirecttradeyesplzBushwickcredenimexercitation8-bitpinterestgreenjuiceBeforetheysoldoutraclettenisisucculentsgatekeepsynthcraypugstreetartnarwhalproidentbespokegentrifylaborisculpaCommodoleggingsironypinteresthelveticaveniamkinfolkVibecessionwaistcoatoccupyaustintry-hardsintwilliamsburgennuitonxelitrampschambraysmallbatchactivatedcharcoalVinylpop-upkeytarincididuntasymmetricalsucculentsheirloomkogisartorialChartreuseedisonbulb+1adaptogenorganicchillwaveloremauteennuiDIYliterallybodegaboyscold-pressedbittersroofpartyaestheticeiusmodnullaumamisameBlogscenesterschlitzipsumvicepariaturestcornholePBR&BorganicForagehelveticasingle-origincoffeegatekeeppariaturmastercleanseuttotebagTemportotebagchurch-keypokpokfingerstacheprismOrganicwhateverbushwickadipisicingroofpartypop-upconsecteturdeepvbeardyesplzPBR&BeverydaycarryhellofbespokeLeggingshealthgothvicefingerstachechurch-keysubwaytileidcronuteverydaycarryYouprobablyhaven'theardofthemknausgaardaustinechoparkcillumcoloringbookidbeardsingle-origincoffeechicharronesbushwickshoreditchrampsexercitationPalosantoreprehenderitpugdistilleryhotchickenhelveticajeanshortswhateverSelvagehashtagpabstmollitchicharronesnextlevelmlkshkvaporwarelisticlekalechipstweeStreetartpickledairplantdisruptcommodocredumamiartpartyennuitry-hardminimfannypackwokeAutebodegaboystaxidermybespokeSynthmumblecoresartorialinclicheeudreamcatcherkeytarquiscraftbeeriPhonekeffiyehraclettemehSusvexillologistculpaputabirdonityouprobablyhaven'theardofthemListicleloremeamarfaliterallyleggingsCardiganintelligentsiakalechipsfannypackartpartyfoodtruckmanbunflannellaborereadymadebanjobittersPokpokquinoaincididuntmollithumblebraghelveticaauthenticConsecteturhoodiebutcherbrunchHelveticaletterpresseutildeyouprobablyhaven'theardofthemwilliamsburgfourlokoflexitarianArtpartyaffogatotousledbanhmiedisonbulbnostrudelitdoloreasymmetricalScenesterhammockbodegaboystbhwayfarersyrutcronutunicornproidentEdisonbulbbitterscoppermugwaistcoatsemioticshotchickendeepvfourlokomixtapestumptownmustacheblogUtfitadbiodieselblogadaptogenpraxismastercleansemigasaffogatoseitanascotMastercleansesedafsucculentsyesplzfarm-to-tablekogifannypackorganickombucharampsascottypewritergastropubPoutinechiaofficiabanhmiChicharronesstumptownmehmlkshklaborecillumaustin3wolfmoongluten-freepokpokTofucronutcoppermugduisyrquinoaartpartyeaoccaecatcardiganmustacheexercitationLiterallytweeblognonviralfourlokocredCommodoslow-carbaestheticsedTumblrhoodiepabstsustainabletbhcoloringbookbeforetheysoldoutpugnullaportlandmigasroofpartyYuccieestthundercatsvinyltbhlyftpugullamcomanbraidsustainableEstbluebottleBrooklynsrirachashoreditchIcelandVHScupidatatsalviadreamcatcherintelligentsiaetsyfranzentumblrjianbingeiusmodmessengerbagVexillologistveniamliterallyquinoaafknausgaardorganiccardigansemioticsveganeawhateverUtetsypabstflexitarianadipisicingesselyftaliquaadeverydaycarryglossierPorkbellymollitintelligentsiacornholeunicorntumericmessengerbagtonxcardiganpitchforkcoloringbookhoodiefingerstacheyuccieflexitarianKinfolkproidentpalosantotofumeggingsvinyllaborumpraxishealthgothfixieullamcoWayfarerseiusmodgluten-freegreenjuiceporkbellyeuschlitzdeepvhashtagvibecessionartisanLumbersexuallive-edgetattooedglossiershabbychicletterpressBigmoodDSAcornholesustainablerampstry-hardcardiganhammockyesplzmanbraidcronutintelligentsiaenamelpinGochujangfarm-to-tableexcepteurdeepvculpaRetrotofuplaidkeytarkickstartercronutaliquaNullamollitnextlevelleggingsviceelitmlkshkSquidexcepteurtbhveniammustacheSucculentssameBrooklynmeggingsreprehenderitvaporwarevexillologistdoloretonxyuccieHumblebragvibecessionclicheputabirdonitmixtapefashionaxeactuallyPBR&BsustainableDeseruntvicevexillologistoccupyskateboardsemioticsletterpresslo-fiechoparksrirachacold-pressedbigmoodAscotneutra8-bitshabbychiccraysnackwaveincididuntartisanjianbingbrunchmastercleansedoloreetsyselfiesflannelQuisraclettesemioticswolfviceDoloreprisminbigmoodtotebagkalechipsaliquafugiatlaborumEdisonbulbDSAtrustfundechoparkCloudbreadreadymadeanimthundercatscornholeadaptogenraclettehashtagconsecteturquisliterallyutDIYHashtagbanhmihealthgothgatekeepXOXO90'spop-upheirloomumamipitchforkmlkshktrustfundshoreditchcold-pressedtattooedSemioticsvexillologistschlitzsalvialocavorecupidatatphotoboothdolorBiodiesellumbersexualcronutasymmetricalyouprobablyhaven'theardofthemhexagondeepvwokecommodoSlow-carbmumblecoreBrooklynshamanstreetartpalosantomukbangkickstarterNarwhalpitchforkVHSfingerstachemeditationullamcotry-hardmeggingslacroixsrirachaSmallbatchbanjoleggingsdirecttradeBrooklynSalviawhateverveganlive-edgevaporwareullamcoselvageunicornelitthundercatsenamelpinDSAipsumkombuchatypewriterelitaustinIcelandmeggingsheirloomkombuchaforagefourlokoeajianbingputabirdonitSedviceullamcoveniamskateboardvaporwareofficiacardiganculpaMumblecoremlkshklisticleetsybruhkogichiaraclettegodardcoloringbookgentrifyflexitariankombuchasalviaglossierJianbingletterpresstaxidermycommodowayfarerscrucifixechoparkkombuchaleggingsmlkshktypewriterfitenimtonxDeserunttousledennuiskateboardsynthportlandmumblecorenarwhalbeforetheysoldouthexagonhoodieaestheticManbunchambrayneutraanimmessengerbagleggingsughchicharronesbrunchactivatedcharcoalcraftbeerglossiermicrodosingmixtapedoActivatedcharcoalsucculentscraftbeerdisruptVelitenimhoodievaporwarehotchickenknausgaardoccupypour-overlomocupidatatvibecessionpaleoXOXOEstsartorialsnackwavelorempinterestportlandauthenticManbunidcommodobutcherbeforetheysoldouttaxidermytaiyakiMeggingsmanbunblogdeseruntfranzenYOLOdolortaxidermyfannypackdrinkingvinegarwolfSustainablehotchickenvexillologistdeseruntbluebottlealiquipbicyclerightsSmallbatchaffogatochurch-keyfitproidentheirloomlaborebluebottlebushwicknisishamanKeytaryesplzsucculentsbrunchletterpressaestheticascotmixtapeorganicdeepvchicharronesUnicornactuallydoessesuslomoconsecteturafbicyclerightsbrunchtruffautInmlkshkgluten-freehelveticagatekeepvexillologistoccaecatFannypackactivatedcharcoalminimphotoboothseitanJOMOInlaborepraxisvexillologistduisanimcommodosemioticsughexRetrocronutloremplaidwilliamsburgtildeconsecteturIncididuntfingerstacheumamidistillerymixtapeactivatedcharcoalcommodosamevelitgastropubintelligentsiaaustinlocavorecredsalviaKeffiyehartisanpokeflannelminimchiahammockcloudbreadMeggingsplaidkinfolkbiodieseldreamcatcherelittildeMigascommodolomotacostumericflexitarianXOXOcardiganipsumceliaccupidatatkeytarpalosantoTweebutcherpokeorganicethicalfugiatyouprobablyhaven'theardofthemennuiGochujangsedpost-ironicsustainablebiodieselGochujangmastercleansekitschfranzenGatekeepceliacincididuntyesplzmixtapeelitpinterestputabirdonitBrooklynquisedullamcolive-edgehealthgothGreenjuicenisihellofyouprobablyhaven'theardofthemlisticlecornholenarwhaltaxidermyquinoaartpartymarfa3wolfmoonMeditationofficiasrirachaincididuntuthelveticaauthenticlaborisjianbingwaistcoatvelitcupidatateverydaycarryflannelFranzenquicillumveniambeforetheysoldoutLacroixpinteresthellacold-pressedmollitsucculentsvenmoactivatedcharcoaldolor8-bithumblebragwaistcoatdirecttradeGluten-freeYOLO+1heirloomtaxidermyestswagbittersoccupyfingerstachevibecessionconsequatReprehenderitwokepour-oversubwaytilepoutineipsumMustacherawdenimchambraycoppermugSingle-origincoffeeceliacsmallbatchsamedoloregatekeepkeytarsussustainabletaiyakiprismwolfmustacheaestheticaustinDeseruntmarfaintelligentsiaeaactivatedcharcoalscenesterSelfiesmeggingsbutcherproidentdisruptBigmoodfoodtruckBrooklynDIYmumblecoreGochujangbanjotaxidermy3wolfmoonporkbellyjeanshortstonxkeytaretsyshoreditchBanhmiheirloomhelveticabutcherchurch-keyhotchickenAliquipchambraykinfolkadcold-pressedvaporwaremarfa90'svaporwarereadymadeporkbellyJOMObeardNulladreamcatchertbhbanjofreeganeaGodardgluten-freeetsysrirachaplaiddisruptcronutshamanXOXOselvageStumptownshabbychicneutraquiscommodocredsuntminimbodegaboysfashionaxenostrudmolliticelandPBR&BartisanMastercleansefingerstachequisgluten-freevaporwarevelitlaborumveniambanjonextlevelrawdenimnostrudpraxisbeardKitsch90'spokeforagegentrifyvinylBruhselvagescenestersalviaputabirdonitirurebushwickmukbangBiodieseldoloreechoparkkogilaborishelveticachiatofusucculentsyucciehotchickentruffautvapeLaborumcoppermugtumblryucciekogivexillologistpugviceMastercleansein8-bitpalosantoAutetry-hardmanbunpabstfannypackintelligentsiaBrooklyndistilleryGatekeephoodieproidentglossierpitchforkputabirdonitvenmobluebottlevoluptategastropubumamipoutinenormcoreceliacEnamelpinsnackwaveirurechambraydoPost-ironicphotoboothpariaturaesthetictattooedbluebottlecredbushwickoccaecatbigmoodumamiadEdisonbulbheirloompinteresttaiyakiPBR&BairplanthelveticanullaadipisicingvaporwareoffalmigaspitchforkMastercleansemlkshksartorialquialiquipthundercatsdeepvretrojianbingviralechoparketsyMustacheselfiesDIYnormcorepaleosucculentsetbrunchpolaroidhellaKalechipsflannelyouprobablyhaven'theardofthemtumericdeepvYesplzshoreditchcoloringbookputabirdonitaliquipaffogatoVHSautecredvenmoslow-carbLeggingsnormcorebluebottleprismviceglossierPokpokslow-carbicelandpolaroidkombuchasalviabicyclerightsmastercleanseoccaecattumblrreadymadeGentrifygochujangrawdenimtattooedletterpressintelligentsiathundercatsPuglacroix90'sfreeganconsequatschlitzbitterskalechipsuthashtagwokeadbespokedeepvviceYOLOfreeganetaustintry-hardafnarwhalpaleoexcepteurduisconsequatflannelJOMOshabbychicportlandIncididuntullamcobanjounicornchurch-keylumbersexualdoloreVapetaxidermyfourlokosynthpalosantodoedisonbulbSalviadeepvsunttweesustainablegreenjuicegatekeeplaborisstreetartveganbrunchCulpanormcoreexfranzenoffalliterallybiodieselcrayEahoodiegentrifyphotoboothvoluptateDoloriPhonelumbersexuallomoethashtagclichesuntthundercatsrawdenimumamikalechipscoloringbookBushwickgatekeepnisishoreditchleggings90'sjianbingexcepteurInkinfolkfitchurch-keytypewriterpour-overbodegaboyspokeaestheticfannypacktildelaboredeepvDuisauthenticchambraybicyclerightspalosantoprismtildephotoboothmehbushwickgentrifyVoluptatereadymadecoppermugsintcloudbreadelitchambraytemporfourlokomollitrawdenimpop-upkalechipsYrvoluptateduismessengerbagschlitzvinylhumblebragexcepteurXOXOquinoaechoparkfoodtruckenim+1artpartypraxisesthexagonpost-ironicthundercatselitflexitariantofuanimflannelknausgaardculpapokeGastropubpolaroidskateboardpitchforkethicalhellawhateveranimauthenticYOLOeiusmodvicetousledFarm-to-tableyrputabirdonitvaporwareForagelomobittersintofunormcoreportlanddolorpop-upmustachefingerstacheEiusmodcraftbeerdolorechicharronesmlkshkCupidatatbespoketotebaglaborumvoluptateFlexitarianpost-ironiclive-edgeincididuntgentrifyVHSportlandhelveticautpinterestsrirachaWolfvinylullamcogentrifymarfaenamelpinchambrayschlitzsnackwaveshamanFranzenyesplzbutcherkalechipsaffogatomarfahelveticagochujangactivatedcharcoalrampsQuiskogivoluptateedisonbulbforageproidentcronutvibecessioncraylive-edgeenimcillumPraxisfingerstachenostrudpop-upmicrodosingmeditationethicalautebigmoodairplantsemioticsNostrudsynthmumblecoreVHSkitschmustachekalechipsfourdollartoastmastercleansemagnadovapeVoluptatedeepvculpapabstraclettetbhauthenticaliquaduisbespokeumamipokelaborispalosantofit90'sinJOMOascotutIdhumblebragkalechipssustainableesseshoreditchGatekeeplive-edgetbhpitchforkgluten-freeeiusmodhexagontempordoloreumamiwilliamsburgsingle-origincoffeepoutineLyftmollitcardiganbanhmiWayfarersvelitunicornDSAadipisicingtonxroofpartyutexercitationest3wolfmoonmustachemigasdisruptLyftpinterestauthenticpolaroidreprehenderitlacroixactivatedcharcoalfingerstachepraxiscredtweemollitindisruptchurch-keyAscotwokecold-pressedceliacWokewilliamsburgJOMOdolormeggingsjeanshortsfamdeserunthelveticaFamceliacsemioticsgreenjuicebrunchnisiprismstumptownTousledaestheticcillumgastropubnextlevelvexillologistduisestidetsyheirloomeupaleowilliamsburgManbunhammockmastercleanseliterallytbhcupidatatselfiesTumerictweepraxistemporincididuntroofpartytruffaututWolfconsecteturgochujangchiadistilleryleggingsdolorsnackwavesintwaistcoatmeditationQuinoanormcorecommodotry-hardaestheticsintkitschpost-ironictotebagswagtaiyakiIPhonecommodosustry-hardyesplzexercitationmukbangcloudbreadmumblecoreoffalwolfbanhmiartpartyauthentictemporPitchforktbhwilliamsburgleggingsjianbingairplantpickledPop-uplumbersexualvegansamenextlevelvicenarwhalessegluten-freerawdenimughfannypackadIPhoneorganicYOLOBrooklynetartisanvenmodeseruntvicekalechipsseitangatekeepConsequatphotoboothpoutinesustainableculpaidnormcorefranzensalviaViraldrinkingvinegarmeditationporkbellysustainableSlow-carbsameshabbychicbutcherTypewriterennuicoloringbookfithotchickenumamiwayfarerscupidatatkeytargentrify8-bittaxidermylive-edgekombuchaadipisicingButcherenimsedgochujangpinteresteamukbangbodegaboysselfiesbrunchinbushwicktousledPorkbellypickledaustinbluebottlechiaadaptogeninwayfarerskombuchagatekeepretroCloudbreadtildeviralpokpokRoofpartysusrampsbeardlacroixelitpariaturwilliamsburgjianbingsquidminimkeytarculpadosynthCupidatatwolffitmlkshkyouprobablyhaven'theardofthemTaxidermyascotechoparkrawdenimdreamcatcherlaborumnostrudfreeganneutranoncraftbeerdirecttradeartpartystreetartauthenticMinimpost-ironicasymmetricalpop-uprawdenimughJOMOsucculentsumamiconsecteturListicletofuvibecessiontrustfundSkateboardfugiatcloudbreadwilliamsburgughwokescenestertry-hardsubwaytileJOMOcupidatattemporstumptown8-bitfranzenYucciewayfarersneutrafixiecronutautedoloreetanimputabirdonitSelvagehexagonaestheticchillwaveBruhsmallbatchlacroixcillumblogtruffautairplanttousledconsequatQuistumericlo-fiesthotchickenAffogatoletterpressmixtapetumblrveniamsedeverydaycarrymustacheumamiexnormcoreclichePabstexercitationkalechipsennuiselfiesmanbunvelitdistilleryseitanquifourdollartoastlacroixmustacheprismVicesustainablepabstpokpokshamanbitterstaxidermyUmamiknausgaardaffogatokeytarrampsProidentpariaturlaborewokefranzenheirloomIrureporkbellyactuallydreamcatcherviralXOXObrunchcloudbreadjianbingeumigasicelandhellofaestheticcardiganPost-ironiclive-edgecraftbeermlkshkipsumelitmehraclettecoloringbookgatekeepwolforganicMustachetofuporkbellysnackwavewaistcoatcommodoBeforetheysoldoutscenesterprismrampsartisanexcepteurenimseddoloreethicalaustinPortlandtbhfranzennonVHSchartreusewayfarershexagonTbhlaborisechoparkoccaecatmumblecoreadaptogenlyftsusvapedosrirachaauthenticsucculentsFreeganflanneldeseruntmeditationtumblrsnackwavesubwaytilepop-upsmallbatchadbeardquisquinoa90'ssquiddoloreesttotebagadipisicingactivatedcharcoalughfourlokoinVelitcredracletteironysintculpaSedauteskateboardvapepost-ironicelitkitschsquidbespokekeffiyehpokeshoreditchforageestbittersSedrampsscenesterorganicinveniamfarm-to-tablefranzenjianbingsuntlyftRoofpartyughauthenticportlandVHSlyftaustinvenmodreamcatcherlomoinRacletteletterpresstildevenmotemporullamcopop-upidreprehenderitnisitonxleggingsgentrifyHexagonbigmoodsartorialoccaecatidkickstartervibecessionfitJOMOUllamcoessepaleomeditationjianbingsnackwaveBittersdisruptpraxismukbangadipisicingreprehenderitpickledactivatedcharcoallocavoreBanjoaliquabanhmiughaffogatosusmessengerbagnormcoreBrooklynpost-ironicfingerstachedolorequinoaSuntnextlevelglossierreprehenderiteverydaycarrylacroixyesplzlaboresubwaytileelitretrocronutmustachesquidorganicTumericchurch-keyhellofBrooklynsquidchiapour-overkickstarter+1aute3wolfmoonShoreditchkalechipsphotoboothcupidatatcrednonaustinullamcodoloretousledvinyltaiyaki8-bitfourdollartoastwilliamsburgPariaturanimtildefoodtruckcoloringbookwokefourdollartoasteverydaycarrykitschyucciedeepvtweeMinimullamcoanimvegansintquissubwaytilenostrudmumblecorehexagonpickledseitanHammockfourdollartoastbiodieseltruffautscenestertry-hardXOXOAliquipkalechipskeffiyehmeditationdeepvechoparkdeseruntFashionaxeveganoccaecatyesplzwayfarersoccupyDIYchartreusequisfannypackeverydaycarrySchlitzreprehenderitlive-edgecredfashionaxefourlokocronutmollitethicalSnackwaveexcepteurchambray+1tattooedswaggreenjuicepokeutcraybespokelacroixasymmetricalglossierVexillologistesseaffogatowokequispour-overenamelpingastropubEuYOLOtumblrfarm-to-tableirureunicornheirloompokpokenimFoodtruckmehbushwickmeggingsmlkshkcornholeoffalculpapariatureathundercatsheirloomleggingsselvagecommodoUllamcosedrawdenimtweeDolorecommodogastropubgodardbluebottlemukbangXOXOlomocoppermugmagnaMehbeforetheysoldoutconsecteturfreeganmukbangDIYpokefannypacksunttofuNonlive-edgemukbangartisanelitliterallyMastercleansevaporwaremicrodosingjeanshortsactuallyfugiatPoutineyrfixiecrucifixestyuccieBrooklynkinfolksussemioticsvinylmarfadoDistilleryinfourdollartoastasymmetricalartpartypokecoloringbooklaborumfranzengreenjuiceauthenticBigmoodesseveganselfiesmessengerbagedisonbulbinpaleoenamelpinnonJOMOmarfahashtagdirecttradeHashtagmeggingsfourdollartoastveniamculpalo-ficoppermugsintbicyclerightsTaiyakiminimnullalocavoredistilleryYouprobablyhaven'theardofthemshoreditchutPBR&BbushwickmeditationadipisicingJOMOlaborumFitkeytarvaporwarebrunchtry-hardlomoyesplztumericaffogatotaxidermyfugiatTruffautincididunticeland+1ascotbluebottleyuccieskateboardBeforetheysoldoutnarwhaldistilleryhellaFreeganschlitzgentrifyportlandbrunchtemporEttonxdistilleryartisanchiamanbraidbodegaboysDIYpinterestkombuchawilliamsburghumblebragquinoanullaSelvagevaporwareneutraskateboardclichedolorheirloomtemporutsalviaquinoaenimlomotruffautJianbingetfranzenaestheticvaporwarecoloringbookDeepvseitandirecttradevapebruhlomoInirurevapetemportousledsuntedisonbulbclicheKickstartertotebagdirecttradetaxidermyidexercitationtousledSchlitzPBR&B+1salviaselfiesbeardNormcoreadsamesingle-origincoffeepugtruffautadaptogen3wolfmoondoloreManbraidsrirachaaliquaseitanlo-fibiodieselrampsfixieProidentfannypackphotoboothiPhonegatekeepviceSelvageportlandtumericeuchartreuseetsyshoreditchutTofudirecttradesusforageunicornechoparkbeforetheysoldoutfannypackutskateboardFamsquidvexillologistshabbychicvenmosucculentstumerictaiyakiSeitankeytarstumptownglossiersnackwavemeggingsmigascillumfannypackcornholeClichebruhneutrachurch-keygatekeepphotoboothmicrodosingVeniamdoloreofficiachambraychartreuselomogreenjuiceTonxshoreditchtattooedcronutgatekeepViralshabbychicbeforetheysoldouteiusmodAdipisicingnullacoloringbookbeforetheysoldoutDistillerybushwickiPhonemagnafannypackflexitarianlisticleBluebottleforagevoluptateeverydaycarryipsumjianbinghotchickenyouprobablyhaven'theardofthemlaborumKogichillwavekeffiyehreadymadeyesplzracletteColoringbookafofficiakickstarteradipisicinggodardColoringbooknormcoregochujangnullamukbangconsecteturbluebottlebiodieselminimhellakombuchakalechipsfamfreeganIdyouprobablyhaven'theardofthemlive-edgecraydolorelisticlepinterestVHSceliacughkeytarsunt3wolfmoonhellaskateboardEtknausgaardjeanshortsfugiatloremyuccielaborumcardiganJianbingDSAadipisicingethicalnextlevelhealthgothDIYsnackwavelomonextleveldirecttradeVibecessiontruffautchartreuseennuianimfranzenduissquiddoloremehracletteLiterally3wolfmoonblogsustainableipsumpolaroidVHSmixtapetattooedIntelligentsiapinterestbeardtotebagfranzencloudbreaddrinkingvinegarscenesternextlevelgastropubprismnonbeforetheysoldoutIntelligentsiaascotputabirdonitDIYcraftbeerkeytarvelitretrolocavoreportlandflannelloremfingerstacheJOMOoccupyglossierlisticleswagaliquipeiusmodenimkitschnextleveltumblrshamandeepvUmamilaboristweekickstarteraliquaplaidvinylyrpugcold-pressednostrudvicemehsedpop-upSubwaytileglossiervexillologistchiaanimVHSbanhmiwhateversintswaghashtagcronutculpaBicyclerightsmukbangDSAcredshamanpour-overAdaptogenvirallo-fichicharronesfranzenpokpokrawdenimnontaiyakischlitzMessengerbagprismstumptowntofutry-hardvexillologistMeditationmarfastumptownbruhfreeganreadymadeselfieswayfarersoccupycardiganchicharroneswolfbiodieselutAdaptogenpokeeashoreditchyriPhoneexercitationwokehexagonfamseitanfreeganSquidshaman3wolfmoonvapealiquatotebagKombucha90'sfitsustildeoccaecatfannypackpost-ironicduisenimmehdistilleryedisonbulbgreenjuicemeditationCillumsalviaculpanongochujangairplantchiavaporwareirurebushwickgastropubkinfolkrampsSartorialbicyclerightshoodieipsumscenesterdeseruntknausgaardkeffiyehedisonbulbkickstarternisifamVoluptatecupidatatlumbersexualauthentictofuenimirurelacroixtumericnonestmastercleanseenamelpinpost-ironicChurch-keysameDSAdrinkingvinegarporkbellyYucciechianoneverydaycarrygluten-freewaistcoatBluebottlesrirachaVHSethicaleuicelandextildefoodtruckfugiatceliacMessengerbagexoffalreprehenderitasymmetricalfranzenexercitationcardiganenimchiataiyakideepvmanbraidDolorselfiesvibecessionneutrautmessengerbagstreetartflannelknausgaardrawdenimCeliacipsumfixieoccaecatselvagekeffiyehgreenjuicebrunchlocavoreenamelpinbushwickkeytarchicharronesvicepugDisruptsemioticsvoluptategochujangmigasadaptogenmagnasingle-origincoffeehelveticalyftsartorialsucculentsFixiesunttonxtofunontumericwolftrustfundtweehexagon3wolfmooncraykeffiyehbanjoChicharronestry-hardvelitdisruptintelligentsiawaistcoatcredtildehoodiechurch-keysrirachadoloregatekeepmessengerbagSedbespokeennuipinterestdoloremanbunfixiepokelomoPaleolacroixreprehenderitglossierkogivoluptatedirecttradelaborisnormcorecoppermugneutrataiyakihellofselfiesintelligentsiaGlossiersmallbatchbiodieselbluebottlenonhotchickensucculentshelveticathundercatsshamantaxidermyracletteelitManbraidkickstarterenimpour-overidtruffautnontry-hardutVaporwaretemporenimasymmetricalfreeganbiodieselDirecttradehoodiefarm-to-tableloremorganicleggingspost-ironicSwagadaptogenidbluebottlepinterestPBR&BfitsynthportlandpitchforkbitterssmallbatchSartorial3wolfmoonadpabsteuYOLOmastercleanseofficiabigmoodsedtildepariaturscenesteretEnamelpinschlitzfourlokoedisonbulbpour-overidwayfarersdotypewriterPokeminimmanbraidgodardaliquaiPhonemehbittersplaidcloudbreadDSAtousledactivatedcharcoalmigasflexitarianQuiJOMOlaborehumblebragaffogatofixieglossierDeepvyuccienisiwaistcoatcoppermugCillumculpacommodogastropubeulocavoreeiusmodpost-ironictumericwhateverWolfselvagevenmofoodtrucklomowhateverutFarm-to-tableullamcooccupykeffiyehelitflexitariandreamcatcherlaborisfourdollartoastascotbittersExercitationutechoparkeiusmodJOMOchiaCupidatatdistillerypariaturlaborefourlokoporkbellyironyBrooklynOfficiafingerstachelomoeverydaycarrythundercatsnormcoreflannelminimaustinfashionaxeclicheairplantUllamcoartpartytweelyftsingle-origincoffeeveganbicyclerightsvexillologisttumblrshabbychicDSAexercitationdeepvkeytarCupidatatinmixtapemessengerbagbanjoplaidhexagonhelveticacold-pressedconsecteturPalosantonormcoreiPhonegentrifyPBR&BdistilleryasymmetricalairplantpickledpitchforkroofpartyirurebrunchkitschsynthUghsrirachabespokegreenjuicepoketumericlaborisbrunchJeanshortskickstartertousledeiusmodaffogatoGodardlomomessengerbagmumblecorecillumtrustfundshabbychicdoEthicallyftnormcorevinylvibecessionwolfvelitPop-upfourdollartoasttaxidermyaliquipkeffiyehactuallyhotchickenrawdenimaffogatoKogiportlandfannypacksuntvapemagnahammock90'sbeforetheysoldouttemporbanjoiPhonechillwavedrinkingvinegarCoppermugfambicyclerightsnormcoreoccupyicelandnostrudtonxfixiepoutineincididuntkitschtypewriterReadymadelive-edgetry-hardintelligentsiamollitcilluminmagnanormcorefarm-to-tablekogieumukbangFugiatessefamtweegentrifypost-ironicbutcherVHSennuileggingshumblebragbittersplaidnontumericVHScrucifixquimixtapetruffautmigaslocavoreinneutrayuccieretroairplantcronutfingerstacheStreetartfoodtruckenamelpinaustinprismsunttumblrcupidatatdreamcatchershamanMustachevoluptateechoparksalviamukbangmicrodosingutswagtry-hardliterallytattooedgodardmlkshkstreetartHammockfannypacksubwaytilecupidatatclichevenmo8-bitchartreusesuntmollitdeepvinCold-pressedputabirdonittemporchillwaveblogetsybutchertofumustacheirurekombuchaquiKnausgaardsmallbatchroofpartyhelveticafamnarwhalsynthironywolfkeytareverydaycarryaffogatothundercatshealthgothTaiyakifoodtruckXOXOvinyllaborislaborumtotebagmehstreetartIntelligentsiahammockgreenjuiceeiusmodlocavorebitterssartorialgentrifypaleoSinthellofethicalconsecteturvinylcronutlocavoreeamigaspour-overumami3wolfmoontweeXOXOmarfatousledactuallymixtape8-bitsartoriallo-fiedisonbulbHelloftumericjeanshortsinadaptogenslow-carbsmallbatchfreegantotebaganimSintfreeganfugiatcupidatatipsumlo-fiprismechoparkWaistcoatipsummeditationneutranarwhalstumptownporkbellyUnicornnostrudporkbellychicharronesdreamcatcherpoutineRampspoutineschlitzcornholeeadoloreChartreuseelitbeforetheysoldoutoccaecathellofUthoodielacroixyouprobablyhaven'theardofthemCommodoullamconarwhalveniamskateboardintelligentsiamicrodosingeiusmodLive-edgehumblebragetbruhintelligentsiamigasflexitarianDIYChiaironyutunicornpariaturautemeditationjianbingyesplzvelitmanbraidenimfixieExcepteurinmigasVHSdreamcatcherlaborumUtironybluebottleintelligentsiaanimselfiesPolaroidleggingspinterestswagYesplzechoparkvaporwareeiusmodvoluptateesseadaptogenIntelligentsiafourdollartoastorganicpinteresttildesustainableduisPBR&Bscenesterfugiatechoparkpost-ironicScenestergodardenimkinfolkfourlokogentrifymollitMagnaactuallynontaxidermyshabbychicanimkeffiyehtotebagFarm-to-tableullamcoesselacroixNextlevelinculpamagnaduisdrinkingvinegarexadaptogenartisanbodegaboyssalviachillwaveMagnaincididunttousledcardiganblog8-bittrustfundadaptogenvinylpickledMeggingspickledkombuchaschlitzyouprobablyhaven'theardofthemenamelpintemporclicheautetonxCeliacascothashtagsusadfourdollartoastcrucifixkickstarterRampsretronostrudedisonbulbsalviadolorcraysustainableceliacinartpartyHelveticawhatevertattooedvelitmukbangbutcherutSedgodardphotoboothreprehenderitincididuntvapetbhskateboardhammockchiaiPhoneipsumkitschlyftFannypackdoloranimfixiequisskateboardchurch-keybanjoincididuntLoremsingle-origincoffeedisruptdolorascotkeytarchiatousledoccupyVHSprismafactivatedcharcoalaliquacrayVelitviralicelandtonxBluebottlelomosalviawaistcoatVHSPhotoboothgastropubfranzenknausgaardmehetdistilleryadipisicingeiusmodhoodiebespokesamestumptownsingle-origincoffeeKnausgaardanimkogismallbatchnonvaporwaredreamcatchercoloringbookdrinkingvinegarvapepolaroidrawdenimveniamputabirdonitgluten-freeBruhdisruptgodardinAdaptogenvegantildechillwavealiquachicharronesBrooklynretrototebagbeforetheysoldoutmeggingsbespokevexillologistchillwaveadYOLOvenmoEuroofpartylisticleetrawdenimtbhinPBR&BexadveganvinylcraftbeermastercleanseDSASuntkalechipsmagnasintbigmoodselfiesadautedistillerybanjomixtapefourlokoAutevaporwaremanbunbanhmicraftbeerthundercatstbhgluten-freemarfaretroairplantHealthgothslow-carbthundercatsaliquavelitpop-uplaborecrucifixchiafashionaxebruhFixielaborumsuntsrirachaenamelpinkickstartermigascoloringbookpugconsecteturroofpartyflannelneutratweeUnicornsucculentsartpartyicelandfamfannypackChicharronesdreamcatchervelitJOMOutoffalneutrakombuchatruffautnormcoreyuccieportlandsubwaytileVHSAdgreenjuiceeverydaycarrytotebagblogaf90'sDIYDolorealiquippariaturascotvape90'ssusleggingstotebagdeseruntliterallyYuccieveganslow-carbpost-ironicidumamikalechipsbespokequiJOMOskateboardwilliamsburgcredSwagfarm-to-tableincididuntsubwaytilekickstarterorganicthundercatsSintmanbraidpokefixieviral90'scillumvelitFlexitarianadjianbingactuallywaistcoattumblrdolorekeffiyehestDirecttraderawdenimethicalgochujangvenmovibecessionHexagonquicornholesucculentsbespokeartpartyofficiaslow-carbgluten-freeactuallyaestheticshoreditchleggingsMagnalive-edgereadymadesartorialinmustachepitchforksedjianbingtypewriterPlaidbanjochambrayblogletterpressmixtapewokefingerstachecronutconsequattry-hardhoodiecommodobeforetheysoldoutgastropubTumericracletteflannelactivatedcharcoaleverydaycarrygastropubenamelpinbigmoodactuallysmallbatchminimveganfarm-to-tableConsequatbicyclerightseverydaycarrytry-hardactivatedcharcoaluttaxidermyincididuntcoloringbookadaptogentbhveganQuileggingsblogfreegansingle-origincoffeetweeiPhoneplaiddreamcatcherpabsteaVicesquidkogido+1cronutroofpartyscenesterDIYeiusmodMeggingsfashionaxeexcepteurlacroixmustacheheirloomunicornauthentictumblrchiameditationcillumpugForageXOXObrunchplaidceliacnostrudsusbiodieselmastercleansemustachelocavoreeverydaycarryAestheticshoreditchsustainablereprehenderitheirloomswagScenestertilderacletteleggingscrayfixieutofficiamlkshkDIYWhatevermastercleansefitfannypacktbhnullawayfarerssynthmumblecorevinyltaiyakiTemporPBR&Bvexillologistlo-fiiruresamepost-ironicairplantidbiodieselneutrahexagonglossierseitanPutabirdonitechoparkgatekeeppalosantofingerstacheoffalethicalDIYflanneltweeBeardroofparty8-bitactuallyhoodieadaptogenexfourdollartoastportlandaffogatoidfranzenunicornColoringbookloremveniamadaptogenactivatedcharcoalmehyesplzcillumveganaliquipDIYthundercatslaboredoloretweetaxidermyorganic+1YOLOkeytarvoluptateoffalSintJOMOpaleoneutradistillerychiaartpartytaxidermyknausgaardpabstMastercleanseanimmagnaputabirdonitkeytarvicegastropubloremnostrudsynthGastropubpaleoethicalputabirdonitveniameusrirachahumblebragsustainablehotchickenkeytarbeforetheysoldoutEverydaycarryculpaoccupyrampssustainableCulpashamansucculentswilliamsburgyrfamdoloreyouprobablyhaven'theardofthembanjoHoodiehumblebragproidentnonyreiusmoddisruptwaistcoatgodardsnackwaveBrooklynnostrudnormcoreceliaccraftbeereiusmodethicalviceautebluebottlevapebittersshabbychic90'sTruffautphotoboothporkbellyreprehenderitnullaexcepteurfingerstachegluten-freeeiusmodtemporutfitkeytarpabstoccaecatHellaenamelpinvirallaboreracletteMukbangpokpokcoloringbooklorembrunchsubwaytilesuntpickledmagnahellaeaWolfestquismallbatchDSApoutinekogiputabirdonitsnackwavekeffiyehlomoaffogatoughkeytarNeutrafugiatauthenticbutcherfashionaxeHotchickensynthtaxidermygodarddolordisrupteaKombucharoofpartysucculentsidQuinoafashionaxeestmicrodosingsnackwavemarfafamGodardknausgaardquisconsecteturaliquadolorefourdollartoasthellabutcherinpaleoNonorganictempormukbangvinylofficiayucciebanjolacroixmessengerbagselfiesechoparkPBR&BglossierwilliamsburgPorkbellypop-upmanbunjianbingetflexitarianbanjoumamiliterallygluten-freeofficiascenesternostrudWolfcredpickledlaboregentrifyVHSasymmetricalbiodieselwilliamsburgTemporBrooklyndeseruntafumamiXOXOtweelacroixLive-edgetumblrtousledessesalviaorganicgatekeepFlannelbanjoculpaincididuntascotviceyesplzrawdenimtweeblogbespokegluten-freeironyofficiaGochujangpugsustainablelaboristaiyakiKombuchaquisJOMOwhateverPugmukbangfourdollartoastfugiatsemioticsanimBrooklynneutrafarm-to-tableairplantBeardnarwhalfashionaxeYOLOoccupyArtpartyadpop-updoloreFingerstacheBrooklynascotmessengerbaglomo8-bitbittersbutcherchurch-keyStreetarttry-hardinhellofPolaroidlyftdrinkingvinegarjeanshortsPutabirdonitinchurch-keyhammocksuntaliquiputfingerstache8-bitVenmomustachelaboretbhhelveticafingerstacheicelanddoloremicrodosinglisticlePinterestkombuchalisticlelaborumvenmocrayelitVHSNormcoretruffautnarwhalkogiPalosantoschlitzyouprobablyhaven'theardofthemtonxscenesterFamcornholeeiusmodcardiganexiPhoneveganvoluptateMeggingsullamcout+1chialaboriswayfarersscenesterlocavoreSmallbatchkinfolklacroixmixtapeyouprobablyhaven'theardofthemhammocklaborisreprehenderitroofpartyfampour-overoffalTonxdolorconsequatheirloomcrucifixpaleochiaexercitationchillwaveneutraanimrampsDistilleryasymmetricaltemporshabbychicpost-ironicwoketry-hardorganicbigmoodDIYaliquipHellofauthentichellatrustfundlacroixEssequisalviaoccaecatdreamcatchertousledorganicsamePolaroidestafpickledjianbingneutraAustinDIYutscenesteroccaecatyrracletteadipisicingtry-hardletterpresseaestYuccieexsedviralsusfugiatvegandistillerywilliamsburgporkbellyPBR&BofficiashamaneverydaycarryYesplzexercitationsquidfannypackNisilocavorebespokeretroscenestertotebagPinterestheirloompoutinemixtapewaistcoatmlkshkkalechipsnullalyftquisIpsumdohoodiecardiganchicharroneswayfarersswagnisiartpartycoloringbooketsyetlumbersexualSuntsusfithumblebragkalechipsveniamgodardretroorganicneutraswagactuallyChurch-keyrampsstreetartsameInportlandpop-upconsecteturBrooklynutnormcorepinterestauthentictonxinIncididuntscenesterfixiefranzenlaborumgastropubminimtruffautPBR&BtumblraliqualyftheirloommixtapeproidentKnausgaardnostrudoccaecatduissusadipisicingvibecessionextweelive-edgerampssalviaEnnuiadipisicingscenesterlo-fiLaborumairplantputabirdonitwhateverbluebottlemessengerbagpop-upnisiidchartreusemustachebutcherpraxislyftlomoProidentpoutinedeseruntsnackwavetumericreprehenderitchiagreenjuicekeffiyehconsequatumamiveniamadipisicinganimchambrayInPBR&Bwayfarershealthgothoccaecathelloflocavorecoppermugexercitationtruffautporkbellycornholeaestheticyouprobablyhaven'theardofthemTumericedisonbulblumbersexualkitschveganretropop-upsalviaplaidstreetartraclettegochujangEnnuidreamcatchervinylclichepost-ironicStreetartvaporwarenullaheirloomauthentickombuchacoppermughumblebragofficiaartpartypalosantoenimbeardmeggingsPBR&Bsingle-origincoffeepokecrucifixCold-pressedfamennuisintaustininmastercleansevenmotumericmumblecoreesseEverydaycarrykitschdeserunt8-bitproidentkogidisruptneutrasustainableactivatedcharcoalViralcoppermugdrinkingvinegartofuproidentsartorialEthicaladaptogenkeffiyehskateboardtemporvaporwarefamcraysustbhDummytext?Morelikedummythicctextamirite?`;

function trim() {
  let output = dummytext.replace(/ |\.|,/g, "");
  fs.writeFileSync("output.txt", output, { flag: "a+" });
}

function showLength() {
  console.log(dummytext.length);
}

function genUsers(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 36774, (i % 36774) + gap) +
      " " +
      dummytext.slice((i % 36774) + gap, (i % 36774) + randomSize() + gap);
    let output = `INSERT INTO users (name, release) VALUES ('${text}',${randomDate()});\n`;
    fs.writeFileSync("users-seed.sql", output, { flag: "a+" });
    if (i === 0) {
      console.log("starting users");
    } else if (i % 10000 === 0) {
      console.log(`passing ${i / 1000000} million users`);
    }
  }
  console.log("finished users");
}

function genAlbums(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 36774, (i % 36774) + gap) +
      " " +
      dummytext.slice((i % 36774) + gap, (i % 36774) + randomSize() + gap);
    let output = `INSERT INTO albums (name, release) VALUES ('${text}',${randomDate()});\n`;
    fs.writeFileSync("albums-seed.sql", output, { flag: "a+" });
    if (i === 0) {
      console.log("starting albums");
    } else if (i % 10000 === 0) {
      console.log(`passing ${i / 1000000} million albums`);
    }
  }
  console.log("finished albums");
}

function genArtists(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 36774, (i % 36774) + gap) +
      " " +
      dummytext.slice((i % 36774) + gap, (i % 36774) + randomSize() + gap);
    let output = `INSERT INTO artists (name) VALUES ('${dummytext.slice(
      i % 43596,
      (i % 43596) + randomSize()
    )}');\n`;
    fs.writeFileSync("artists-seed.sql", output, { flag: "a+" });
    if (i === 0) {
      console.log("starting artists");
    } else if (i % 10000 === 0) {
      console.log(`passing ${i / 1000000} million artists`);
    }
  }
  console.log("finished artists");
}

function genPlaylists(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 36774, (i % 36774) + gap) +
      " " +
      dummytext.slice((i % 36774) + gap, (i % 36774) + randomSize() + gap);
    let output = `INSERT INTO playlists (name, song_count) VALUES ('${text}',${randomSongCount()});\n`;
    fs.writeFileSync("playlists-seed.sql", output, { flag: "a+" });
    if (i === 0) {
      console.log("starting playlists");
    } else if (i % 10000 === 0) {
      console.log(`passing ${i / 1000000} million playlists`);
    }
  }
  console.log("finished playlists");
}

function genGenres(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 36774, (i % 36774) + gap) +
      " " +
      dummytext.slice((i % 36774) + gap, (i % 36774) + randomSize() + gap);
    let output = `INSERT INTO genres (name) VALUES ('${dummytext.slice(
      i % 43596,
      (i % 43596) + randomSize()
    )}');\n`;
    fs.writeFileSync("genres-seed.sql", output, { flag: "a+" });
    if (i === 0) {
      console.log("starting genres");
    } else if (i % 10000 === 0) {
      console.log(`passing ${i / 1000000} million genres`);
    }
  }
  console.log("finished genres");
}

function genSongs(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 36774, (i % 36774) + gap) +
      " " +
      dummytext.slice((i % 36774) + gap, (i % 36774) + randomSize() + gap);
    let output = `INSERT INTO songs (name, genre, length, listens) VALUES ('${text}','${randomGenre()}',${randomLength()}, ${randomListens()});\n`;
    fs.writeFileSync("songs-seed.sql", output, { flag: "a+" });
    if (i === 0) {
      console.log("starting songs");
    } else if (i % 10000 === 0) {
      console.log(`passing ${i / 1000000} million songs`);
    }
  }
  console.log("finished songs");
}

// Generate a random song length in seconds from 60s to 360s
function randomLength() {
  return Math.floor(Math.random() * 300 + 60);
}

// Random song count for playlists
function randomSongCount() {
  return Math.floor(Math.random() * 45 + 5);
}

// Generate name length randomly
function randomSize() {
  return Math.floor(Math.random() * 8 + 2);
}

// Generate a random listen count, favors lower numbers thanks to square root
function randomListens() {
  return Math.floor((Math.random() * 10000) ** 2);
}

// Random date after 2012
const start = new Date(2012, 0, 1);
const end = new Date();
function randomDate() {
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime())
  );
}

// Brian's genGenres into songs function
const genres = [
  "Blues",
  "Classical",
  "Country",
  "Electronic",
  "Folk",
  "Hip Hop",
  "Jazz",
  "Latin",
  "Pop",
  "R&B",
  "Rock",
  "Alternative",
  "Indie",
  "Punk",
  "Grunge",
  "Metal",
  "Thrash",
  "Death",
  "Black",
  "Doom",
  "Power",
  "Progressive",
  "Symphonic",
  "Technical",
  "Rap",
  "Trap",
  "Gangsta",
  "Boom Bap",
  "Juke",
  "Footwork",
  "Jungle",
  "Drum and Bass",
  "Breakbeat",
  "Dubstep",
  "Trance",
  "Techno",
  "House",
  "Electro",
  "Disco",
  "Funk",
  "Soul",
  "R&B",
  "Hip Hop",
  "Rap",
  "Gospel",
  "Reggae",
  "Ska",
  "Rocksteady",
  "Dancehall",
  "Dub",
  "World",
  "African",
  "Arabic",
  "Chinese",
  "Indian",
  "Japanese",
  "Korean",
  "Latin",
  "Brazilian",
  "Salsa",
  "Merengue",
  "Cumbia",
  "Reggaeton",
  "Tango",
  "Flamenco",
  "Greek",
  "Irish",
  "Scottish",
  "Welsh",
  "English",
  "American",
  "Bluegrass",
  "Cajun",
  "Creole",
  "Delta Blues",
  "Zydeco",
  "Southern Rock",
  "New Orleans Jazz",
  "Chicago Blues",
  "Tex-Mex",
  "Tejano",
  "Nashville Sound",
  "Honky Tonk",
  "Outlaw Country",
  "Country-Rock",
];
function randomGenre() {
  return genres[Math.floor(Math.random() * genres.length)];
}

const gencount = 1000;

// genUsers(gencount);
// genAlbums(gencount);
// genArtists(gencount);
// genGenres(gencount);
// genPlaylists(gencount);
genSongs(100);
