const fs = require('fs');

const dummytext = `Imbabyneutrafreeganpolaroidtildefingerstache+1chiasnackwaveviralmanbraidwilliamsburghoodieNormcoreethicalkeffiyehDIYkogicraftbeergastropubvinylselvageintelligentsiakeytargodardStreetartblogfranzenlive-edgephotoboothYucciefourlokoaustinbitterspalosantobeforetheysoldoutughwilliamsburgcoloringbookartpartyLo-figatekeepfarm-to-tablemumblecorecrucifixVHSfourdollartoastcornhole8-bitnormcoreEnamelpintweehellatotebagBrooklyncronutbespokeasymmetricalfourlokowayfarerskeffiyehVenmolocavoreplaidrawdenimvibecessionyrfannypackorganicmixtapeDSASemioticschurch-keyvinyloffalpokpokbluebottleVapeviralwilliamsburgfitflannelgastropubwaistcoatcronutnarwhalGlossiersrirachawayfarersreadymadeflannelhashtagVHSnarwhalorganicactivatedcharcoalvaporwarecredcrucifixPitchforkhoodietattooedtypewritermehfannypackgodardHealthgothenamelpinlyftlumbersexualpaleovexillologisttonxughhoodieyouprobablyhaventheardofthemcronutnormcoremumblecoreleggingsTaxidermyceliaclyftsartorialclichewaistcoatPrismyuccieforagekeytarmarfaPBR&BtousledJianbingbigmoodmeggingspour-overretroughreadymadefranzenpinteresttumericchicharronesPaleolomoswagprismshoreditchcloudbreadselfiesactuallyVHSdrinkingvinegarretronarwhalcrayDIYKombuchaporkbellycronutjeanshortsdeepvlocavorepokpokviraltonxiPhoneTypewritervibecessionfamviceshamanactuallypinteresttousledkombuchakickstarterJOMOMarfathundercatsbluebottlecoppermuglumbersexualvicecraftbeerfranzentotebagcold-pressedflannelennuiporkbellywhateverTbhvexillologistsrirachaascottotebagbluebottleretroGastropubbloghellofJOMOmlkshksrirachacloudbreadviralMasterJarrettcleanseslow-carbtypewritermessengerbaggastropubManbunthundercatswolftattooedyrHealthgothDIYbanjoactivatedcharcoalSustainablepokpoktumblrDSAbigmoodennuicredoffalforagekeffiyehpabstvirallacroixNarwhalvexillologistiPhonefashionaxepinterestintelligentsiacornholedisruptkickstartertbhheirloomYOLOoccupymarfaDSATumblrtildescenestertrustfundfamfranzenascotshoreditchsubwaytiletweechillwaveHoodieicelandwolfquinoaseitanPBR&Bpour-overmigasmicrodosingmumblecoretonxwhatevergochujangFoodtruckfreeganplaidtacosgatekeepArtpartycredbanjophotoboothSemioticspour-overechoparkmeditationwaistcoattacosVaporwarebittersmeggingswilliamsburghumblebragsrirachaKinfolkbiodieselPBR&BbanjotattooedlyftTofugastropubpaleolive-edgeracletteintelligentsialisticleaestheticShoreditchswagpalosantoviraltypewriterTypewriterbushwickportlandforagehelloflacroixetsyumamiVHSshabbychicmessengerbagpalosantoFarm-to-tablepickledgodardsartorialnarwhalglossiertattooedveganhoodieceliaclo-fiyrbushwickSalviaflexitariantumericvinylFitlyftDSAjeanshortscredRaclettestumptowntumericnarwhalhumblebraggluten-freecoppermugporkbellyBigmoodgochujangenamelpinreadymadepinteresttotebaggentrifyEchoparkkalechipsbrunchDSASchlitzmigasjeanshortscronuttumericneutraFranzensemioticswayfarersfourdollartoastbiodieselreadymadevibecessionhellofknausgaardtotebagbanhmiTildeunicornbespokesubwaytilecornholeartisanpokeicelandjeanshortsyouprobablyhaventheardofthemvapeTattooedchicharronescoloringbook+1manbraidtry-hardennuiCornholeshamanlumbersexualbeardgatekeepskateboardenamelpinkitschprismMustachefashionaxeswagbruhdeepvracletteViralcardiganvicetypewritertumblrRawdenimbespokefranzenkinfolkkombuchaicelandscenester3wolfmoontousledcardigancoppermugsmallbatchmixtapeironyhammockkombuchajeanshortsyesplzkeffiyehbanhmichurch-keySelvagekalechipspraxismukbangforageetsychicharronescrucifixyesplzwolfSkateboarddisruptcornholewokeXOXODSAmixtapeYOLObruhliterallyLive-edgemeggingsfarm-to-tableceliacnormcoremehtacosgluten-freeoffalyouprobablyhaventheardofthemgatekeepVHSmehplaidsamewolftacoschicharronesthundercatshammockSlow-carbyrjianbingselfiesmessengerbagheirloomwilliamsburgbitterspokemixtapemehchiaenamelpinknausgaardManbraidgentrifytrustfundmlkshkpraxistotebagknausgaardmastercleanseBrooklynpokeFamviralcoppermugcold-pressedmicrodosingactivatedcharcoalsusmessengerbagbittersmastercleanseTry-hardyucciepoutinecold-pressedSemioticsyesplzskateboardfashionaxetweeBrooklynintelligentsiatrustfundethicalhoodiefourdollartoastactivatedcharcoalgatekeepTrustfundhellavicevenmoPhotoboothwilliamsburghoodieFernandotaxidermygatekeepdreamcatcherpaleoneutralo-fiRetroascothellacardigantattooedlo-fipop-uppaleohoodie8-bitshamanBluebottlevaporwareshamanpaleodisrupttbhdreamcatchertotebagsynthmanbraidkeytarVexillologisttweelocavoreleggingsmehsubwaytilehelveticadrinkingvinegarvibecessionsemioticsslow-carbbutcherechoparkHella+1VHSviraltofupokpokpaleogatekeepmessengerbagtattooedbeforetheysoldoutswagfamnextlevelmustacheCraychicharronestildeplaidMastercleansebigmoodsushumblebragnormcoreNarwhalethicalpugseitan3wolfmoonhammocksusreadymadeyucciesingle-origincoffeeporkbellyshaman90sFixieschlitztonxbrunchHotchickenvexillologistgastropubtweeleggingsascotmessengerbagnarwhalennuifreeganPugdreamcatcherwayfarerskitschgreenjuicelisticlepaleoliterallysquidtildefannypackroofpartyDIYheirloomMixtapereadymaderaclettehumblebragsucculentsunicornlacroixgentrifyactuallyaftattooedstreetartFourdollartoastscenesterwaistcoatbiodieselfixiesucculentsflexitarianchurch-keygluten-freeairplantKeffiyehbeardseitanmessengerbagdrinkingvinegaradaptogengluten-freetattooedreadymadekombuchakickstarterquinoavexillologistlo-fitrustfundRampssubwaytileprismslow-carbcold-pressedstreetartClichefamvibecessionblogdreamcatchertypewriterwolfselfiesneutrasalviakinfolkSchlitzsrirachasartorialoffalennuiheirloomasymmetricalDrinkingvinegarpugwhateverschlitzkeffiyehscenesterforageascottofuvirallyfthealthgothhoodiesemioticsmixtapeTildeyuccieprismiPhoneethicaladaptogenshabbychicviralyrFlannelactivatedcharcoalasymmetricalportlandtattooedbutcherrawdenimmlkshklomomanbunbanjopolaroidFreegancornhole+1neutraplaidcraymukbangsusbluebottlemlkshkCrayDSApickledmeggingsartpartyJoubanhmiactivatedcharcoalsingle-origincoffeequinoaChambraygentrifyjianbingbodegaboystaxidermypalosantoshamanhumblebraglo-fi+1pop-upvaporwarePraxiswolfvinylvegankalechipsnarwhalgluten-freePBR&Baustinscenestercold-pressedenamelpin+1franzenFourdollartoastslow-carbbanjocornholebigmoodtumblrcraftbeerTbhroofpartycardigansemioticsstumptownswagughmarfa8-bitPop-uptrustfundactivatedcharcoalvibecessionkogiblogBrooklynmumblecoretaiyakitry-hardhellaneutrabicyclerightsfoodtruckManbunhellaintelligentsiapolaroidmeggingsasymmetricalSelvagebeardwilliamsburgwayfarersliterallymicrodosingportlandroofpartyfourlokohellaporkbelly+1fitPost-ironiccredhelloffixiegluten-freeintelligentsiawayfarersdeepvascotselfiesdrinkingvinegargodardblogtacosKitschsamekeytarughmlkshkforagemastercleanseaestheticascotasymmetricalmixtapeKalechipsnarwhalmukbangeverydaycarrycraftbeervape+1greenjuicepop-upironymumblecoredisrupttacosshoreditchbiodieselHealthgothchambraypickledgentrify+1directtradekogibrunchdeepvfixieDistillerysnackwavemukbangtumericcornholeleggingsbluebottleceliacseitanunicornfourdollartoastfoodtruckmicrodosingVaporwaresmallbatchpokpokbeardbluebottlefashionaxepokemessengerbagfourdollartoastvenmosnackwavecredPBR&Bpost-ironiccoloringbookBigmoodgodardfranzenbluebottleironyoffalveganwaistcoatchambraylive-edgepalosantoneutrayesplzNeutratattooedascotcardiganhexagonbittersSchlitzliterallygodardwaistcoatpickledgluten-freeMeggingscold-pressedpokemastercleansechartreuseWaistcoatshamansemioticsvicenarwhaliPhoneoffalreadymadeselfiestruffautflexitarianTruffautironyjianbingmeditationHelveticaedisonbulbnextlevelbluebottleplaidmigasCraftbeeraestheticviralfashionaxetofujeanshortspugtrustfundlive-edgepabstpokehellofliterallyManbraidvenmogreenjuicevaporwarekinfolkdisruptlacroixetsyneutraBicyclerightseverydaycarryputabirdonitkinfolkflannelcornholepaleosustainablesamekombuchaAscot8-bitneutradeepvmeditationBrooklynlomopalosantohoodiegastropubveganSingle-origincoffeedistillerysemioticsmlkshkmixtapejianbinghealthgothaestheticcredsucculentsdirecttradePabstkeytarstreetarthexagonfamPBR&Byesplzwayfarerstacostry-hardhellofportlandorganicLeggingsclichetaiyaki3wolfmoonvexillologistpolaroidgluten-freerampsironyprismArtpartyflexitarian90stousledsquidXOXOshabbychicpugClichetotebagfreegansynthmessengerbaghashtagceliacbrunchfitviceBrooklynpabstEtsykitschumamimastercleanseBeforetheysoldoutshoreditchlacroixartisanBanjoairplantreadymadeedisonbulbretrosametousledhumblebragkinfolkquinoaPabstchicharronesglossierpalosantotattooedwokeletterpresspitchforkpaleomanbunairplantracletteOffaladaptogenaffogatotaxidermyyuccietweetumblrTry-hardironypitchforkactuallyrawdenimpickledflannelmastercleansebicyclerightsNeutracornholehellofroofpartypabstactivatedcharcoalseitan90sbruhretroicelandgluten-freemeditationPrismvaporwarelumbersexualmeggingsfannypackbrunchChillwaveairplanttumericbruhreadymadeplaidnormcoresalviafourlokobutcherLumbersexualshamansrirachasubwaytileintelligentsiasmallbatchcold-pressedknausgaardsamewokeyouprobablyhaventheardofthemPorkbellypickledpitchforkPBR&BfingerstachepoutineMlkshkfannypackgentrifyliterally+1etsytumericfourlokomastercleanseChianeutraDSAkeffiyehhashtagquinoahelloflumbersexualsynthicelandfannypackiPhonechicharronesascotFashionaxehammockrawdenimpoutinegateBriankeepjianbingDIYvaporwareBushwickartisanennuigluten-freekickstartertildemicrodosingsquidpaleomarfa90sKeffiyehgodardbicyclerightsairplantplaidkogimixtapefoodtruckhealthgothFlannelplaidprismpolaroidorganicpoutineportlandKogichillwavebodegaboystrustfundfixieceliachashtagletterpressdisruptCold-pressedgreenjuicecloudbreadtonxdisruptforageeverydaycarryLeggingsennuipop-upadaptogendreamcatchertweeswagkalechipsaffogatowayfarersKickstarterpalosantofourdollartoastpour-oversingle-origincoffeeoffalkalechipsumamisnackwavebeforetheysoldoutaffogatoUghrampsphotoboothdisruptmehvaporwarekeytarChurch-keyhumblebragdreamcatcherhealthgothsustainableselfiesJOMOmeggingsSwagtaiyaki90sfourdollartoastjianbingshoreditchGlossierauthenticactuallytweeSquidsametofurawdenimsalviaactivatedcharcoalvibecessioncoloringbookhammockGentrifybrunchdistilleryhellofhexagonstreetartafviralmeggingsKombuchaplaidbruhsynthportlandJOMOtumblrpokelumbersexualBicyclerightssnackwavegentrifychillwavesingle-origincoffeepokesquidmicrodosingfamcrayprismfixieGastropubtypewriterkalechipsglossiermehbiodieseltumblrsquidsartorialBrooklyntaxidermyquinoasusfarm-to-table90sEverydaycarrychillwaveughdeepvethicalVHSPBR&BgodardheirloomYOLOtaxidermyselfiesSalviasemioticsfarm-to-tablemehmanbunfreeganChartreuselocavoremastercleansemanbungochujangschlitzwokeVHS+1iPhoneTildeJOMObutcherbrunchstreetartpugfranzenlacroixasymmetricalgentrifyfamdistillerymehpinterestretroChartreusesingle-origincoffeejeanshortspour-overkinfolktotebagMlkshkpabstnarwhalbanhmibrunchforagelisticleselfiesschlitzYrauthenticgreenjuicelive-edgeChillwavepost-ironicetsymessengerbagsucculentsUmamifashionaxebutcherraclettetumericshamanfoodtruckblogironytotebaglo-fiseitandisruptMessengerbagironysuscreddirecttradeneutrahashtagennuichiaphotoboothJOMOtaiyakiaustinColoringbookfingerstachelisticlenormcoremukbangnextlevelkalechipsfarm-to-tablekogiYOLOorganiccoppermughammocklyfthashtagXOXOtumericfourdollartoasteverydaycarryfarm-to-tableaestheticdreamcatcherpitchforkgochujangDIYporkbellyTweeJOMOtumericpitchforkgreenjuicekitschshabbychichashtagsucculentsclichelacroixAfchillwavepokpokshabbychicmumblecorelocavorehotchickentildebittersracletteportlandroofpartykogiArtisanseitanJOMOcloudbreadvapetildeintelligentsiaenamelpinpitchforkHashtagbluebottleseitanDIYrawdenimOffalscenesterpalosantotaiyakiyouprobablyhaventheardofthembushwickracletteFingerstacheactivatedcharcoalumamicold-pressedselfiesfreeganYOLObeardfarm-to-tableroofpartyDIYkitschgentrifyintelligentsiataxidermysucculentstildePokefourlokofashionaxefixiepolaroidEnnuicoloringbookechoparknextlevelbutcherlumbersexualglossierorganicetsyughpolaroidhellashabbychicBiodieselfoodtruckwhateverclichepabstpaleolisticlecornholeFoodtruck8-bitquinoanextlevelletterpresshellofhumblebragleggingstbhfarm-to-tableNeutrachiastreetartmanbunmumblecoregastropubDrinkingvinegarquinoabiodieselfourdollartoastAestheticumamiennuitofuroofpartytrustfundTacossingle-origincoffeeartpartytildebigmoodletterpresshexagonethicalkickstarterselfieskombuchastumptownvexillologistSalviafarm-to-tableumamibanhmiVHSjianbingvenmowaistcoatsusartisangentrifypokpokascotpabstArtpartybutcherpokpokpour-overwayfarerstaiyakiedisonbulbActuallywayfarersplaidwaistcoatletterpresssamestumptownnarwhalkeffiyehDirecttradecardiganchillwavepolaroidsustainablekalechipstildepaleomlkshkfourdollartoastauthenticnarwhalviceFourdollartoastlomoletterpresspaleobutcherschlitznormcoreKeffiyehnarwhalmehchambraypokeskateboardpitchforktruffautcraftbeerYesplzgentrifypoutineliterallyfashionaxebeforetheysoldoutpabstfiticelandKnausgaardtofushamancornholehealthgothaffogatogochujanghellabruhsrirachamukbangcoppermugnormcoreshabbychicBruhblogartpartymeggingsDirecttradebushwickkalechipsgochujangkitschtaiyakiDIYDSAswagprismLetterpressbruhwokefixiesynthsmallbatchkogileggingsughsquidkalechipscoloringbookArtpartyselfiesskateboardtonxpugsubwaytileGochujanghumblebragfoodtruckmanbuntaiyakiDSAFitiPhonechicharronesDSAclichechillwavemumblecorepitchforkthundercatssubwaytileEverydaycarryquinoaschlitzsustainableswagBrooklynbodegaboysletterpresssingle-origincoffeepour-overliterallyVicepaleovapeedisonbulblomoNarwhaltweesustumerickeffiyehmustacheetsybanhmistumptownmumblecoretumblrvibecessionsartorialjianbingBittersviceBrooklyndrinkingvinegartrustfundscenesterorganichumblebragslow-carbchurch-key8-bitgreenjuicesameTaxidermymixtapethundercatssemioticsbeforetheysoldoutdreamcatchervirallumbersexualsucculentswokeCornholetacostry-hardveganfranzenleggingsairplantwayfarersumamiyesplzmanbraidwilliamsburgChambraysusretrodistillerymarfachillwavetypewriternarwhalTweebeforetheysoldoutpraxisselvagetousledironyhexagonoccupyfourlokoTousledtypewritertattooedgodardgatekeepethicalThundercatshealthgothaffogatotbhpolaroidtacoskickstarterhashtagtofumanbunumaminormcoresartorialquinoaliterallyKombuchacoppermugfixiemeditationedisonbulbjeanshortsphotoboothJOMOmehDSAgreenjuicesubwaytilefashionaxeretrotaxidermyartpartypitchforkKadynce+1hexagonorganicDIYsmallbatch8-bitpost-ironiciPhonelumbersexuallive-edgeYouprobablyhaventheardofthemfranzenporkbellychillwavedreamcatcherhellofsartorialmanbunorganicManbraidfingerstacheputabirdonitlo-fi+1FingerstachehammockcraycrucifixYOLOsalviahexagonactuallyselfies90smukbangbrunch+1kalechipslacroixOrganictbhsartorialgodardafcrucifixcardiganSchlitzpickledtypewritergluten-free90sjianbingseitancredironyhellachillwaveleggingsnextlevelTumericgreenjuiceflannelnarwhalplaidtbhselvagegastropublo-fiBluebottleafbodegaboysgentrifybiodieselhotchickentattooedbeardhashtagvinyldisruptDIYchiakalechipshoodieClichemukbangvexillologiststumptownglossierairplantputabirdonityucciedistilleryedisonbulbRampsartpartymarfatofuwilliamsburgactuallyaustinRoofpartysustainableenamelpinyouprobablyhaventheardofthemasymmetricalHotchickenumamitweebanhmisartorialpour-overmeditationvinylplaidoffalBushwickwayfarershellavapefannypackwhateverpugtotebagmicrodosingsalvia8-bitunicornschlitzmigasvaporwareHoodielo-fipour-oversubwaytilepraxischillwavetacosbitterscold-pressedVHSpoutinestumptowncornholevapeporkbellyHeirloombiodieselyuccieicelandughstumptownblogtacosPBR&BKalechipsglossierknausgaardseitankeytarputabirdonittaiyakilomoasymmetricalpost-ironicPokeoffalbrunchbushwickvexillologistshamanhealthgothtousledPour-overstreetartheirloomcrayVHS3wolfmoonetsybeardlocavoreHumblebragairplantethicalstumptownsquidvegandeepvdirecttradetweebutcherlisticlebittersTonxkinfolksalviapolaroidstreetartYOLOmeggingsscenesteredisonbulbsustainablegatekeepfameverydaycarrypop-upGlossiercronutedisonbulbhammockfashionaxetotebagpabstwaistcoatmukbangironyechoparkmanbraidunicornmumblecorestreetartTrustfundlive-edgeblogvicekitschYOLOtaiyakikombuchaoccupybushwicksynthughtofu3wolfmoonMukbangwilliamsburgmarfachambrayforagequinoasucculentscraywaistcoatsnackwavevibecessionsartorialhellavenmowayfarersHellasmallbatchsusmustacheporkbellybicyclerightsportlandlocavorecronutsingle-origincoffeeAestheticpoutineDIYkalechipsputabirdonitglossierCeliacpost-ironicDSAasymmetricalWolfethicalaffogatoglossiercraftbeermanbunoffalsameheirloomunicornpoutinestumptowntaiyakihelveticaSucculentsmanbunfashionaxeflexitarianpokpokmumblecorelocavorebodegaboys3wolfmoonmanbraidhealthgothporkbellyXOXOprismtonxscenesterceliactry-hardKeytarmukbangadaptogentattooed90scloudbreadReadymadepickledartpartynarwhalmanbungluten-freebrunchLive-edgemustachecreddistillerytofubespokequinoaJOMODIYunicornorganicyrtweeviralFoodtruckyuccieracletteshabbychiceverydaycarryaffogatocold-pressedjianbingplaidmanbundeepvhammockcloudbreadVexillologisthoodievicebeardtaiyakigentrifymicrodosingrampsbanhmimehbushwickasymmetricaljianbingHashtagVHSskateboardcoloringbookbruhtypewritermukbangsmallbatchshamanvibecessionnarwhalbigmoodEtsyedisonbulbtildehumblebragneutrakeytarkogishoreditchflexitariansartoriallomoceliacmessengerbagyouprobablyhaventheardofthemYOLOPinterestceliacveganpaleopickledswagcraftbeermukbangauthenticlocavorepost-ironicsalviakeffiyehportlandpugAirplantauthenticchicharronescoppermugtypewriterquinoahellofbruhicelandintelligentsia8-bitchillwaveFitpitchforkceliacvegantruffautIPhoneputabirdonitbeforetheysoldoutironyunicornpraxisauthenticleggingsPugcloudbreadpitchforkpinteresttumblrvenmomustacheslow-carblisticledeepvtotebagpour-overkitschmlkshkEthicalpraxismanbraidcardiganletterpressironykinfolkpalosantoveganChicharroneswayfarerseverydaycarrychambrayportlandicelandleggingsceliacairplantselvagesartorialshamanmumblecoreCronutechoparkartpartymigasmixtapeumamiyrSingle-origincoffeepabsthumblebragracletteselvageseitansucculentsquinoatattooedVHSschlitzbanhmipabstsemioticsPutabirdoniticelandmigas3wolfmoonPokefranzensnackwavestumptownquinoa90svibecessionfashionaxebicyclerightsfreeganhellaVicetaxidermytumericreadymadechurch-keymukbangnextlevelhelveticaironycraftbeervibecessionwokeviralkombuchaEdisonbulbJOMOlocavoretrustfundpoutinedrinkingvinegarbruhcronutcoloringbookbanhmichambrayPop-uppugicelandtumblrtattooedforagecronutnarwhalvapegatekeepbanhmiPokpokmukbangpoutinecloudbreadsartorialcronutartisanJOMOmarfaplaidkombuchasrirachabespoketruffautsustainablevenmocornholecraftbeertaxidermyPabstschlitzwilliamsburgtotebagYOLObicyclerightscraychurch-keyBigmoodvapesameairplantraclettekitschJOMOchiamixtapeliterallyasymmetricalfannypacktacossalviaTrustfundvexillologistVHSPBR&BstreetartnormcoreflannelfamwhatevermustachepraxissemioticstildeintelligentsiavinylLive-edgekinfolkhellofoccupy90stotebagliterallykogiAuthenticplaidmeditationsquidfitfamletterpresslyftXOXOchartreusecredBespokesartorialmumblecoresustainablefourdollartoastMixtapeyrtaiyakioffalportlandFourlokobanhmimeggingsmarfabanjolive-edgecardiganbeardaffogatoswagJeanshortsreadymade90sfamorganicethicalclicheechoparkenamelpingochujangseitanchartreusenormcoreLetterpressunicornvenmodrinkingvinegariPhonefreeganseitantumblrMehhammocksquidchurch-keyviceforagehelveticataxidermycrucifixcold-pressedcloudbreadhealthgothdirecttradeTattooedironyfashionaxerampsetsytonxhelveticaeverydaycarryclichetaiyakiVibecessionlo-fiwaistcoatchurch-keyracletteUmamipugliterallybittersyuccietaxidermypitchforkauthenticNeutrayrfamtotebagcronuttweeManbunliterallystumptownasymmetricalfannypackCreddrinkingvinegarsucculentsseitanpabstsartorialsemioticstumericauthenticManbraidpoutinegodardvegansquidmanbunselvagevinylascottacosSriracharaclettekeffiyehbanhmiwokeshoreditchCrucifixDSApickledtonxbicyclerightsyouprobablyhaventheardofthemmehdisruptenamelpinfitfourlokoscenesterTofu90sforagewayfarersleggingsgentrifyvinylfourlokolomoLomobodegaboyssmallbatchbespokemanbraidDSAtaiyakitattooedsnackwaveJacquan+1seitanswagcronutcraftbeersemioticsSnackwavegluten-freeswagjianbingbeardBespokeviralechoparkkeytarfashionaxevinylcrucifixpickledtry-hardwilliamsburgtweenormcorehammocksubwaytilefreeganSubwaytilefourdollartoastnarwhalsingle-origincoffee90skickstarterquinoaXOXOgatekeepyesplzeverydaycarrySchlitzartisanrawdenimpost-ironicactuallyCredadaptogenbespokemarfamigasgastropubenamelpinvenmowokekitschmustacheracletteLive-edgethundercatsvibecessionhellofmeditationliterally3wolfmoonpickledchillwaveyucciepolaroidtbhSkateboardporkbellyschlitzvapelive-edgechillwavewaistcoatXOXOIPhonefourlokosusorganicretrokalechipsstreetartaestheticlomoceliac+1kinfolksquidquinoa8-bitCrucifixscenestertildeoffalintelligentsiafranzenwaistcoatfoodtruckwayfarersdisruptBrooklynlo-fibiodieselethicalEnamelpinrampsasymmetricalauthenticafvinylLumbersexualpost-ironickombuchaiPhoneputabirdonitviralcoppermugglossiertildewaistcoatafFannypackgentrifyfashionaxecoppermugmigaswolfetsyaffogatoActivatedcharcoalmigasslow-carbcraftbeernormcoredirecttradeartisanAscotclichepolaroidvicebruhsynthdreamcatcherartpartysubwaytilecronutsquidRampsschlitzchillwavegatekeepkogijianbingwaistcoatcornholeironysustainableflannelslow-carbDirecttradepitchforksynthchambraymixtapebeardtonxtofuoccupyFamlo-fiironycornholeYOLOfourloko90skogilyfttaxidermyNarwhalthundercatsforagechambrayedisonbulbUghhotchickengastropubasymmetricaldreamcatcherkogigreenjuicetrustfundDistillerywolfblogbespokemanbunschlitzfamretrofashionaxeaestheticauthenticsingle-origincoffeeshabbychicOffalhelveticabushwickhashtagsucculentssmallbatchedisonbulbwhatevervaporwarePrismceliacpickledascotstumptowntacoshealthgothBanhmicraftbeeraffogatovicescenestersynthactuallyseitanbiodieselmehkickstarterrawdenimmanbunpitchforkpugSquidauthenticreadymadeschlitzportlandphotoboothbespokePour-overgreenjuicesnackwavehotchickenflexitariandreamcatcherviralaestheticsalviasemioticssuspokebutcherkalechipssmallbatchMukbangpraxisdirecttradetaiyakibushwickmigaslisticleselvageYOLOtrustfundaestheticbruhcornholeporkbellytumblrbespokevibecessioncloudbreadmeggingsprismTofuactuallyhashtagchiatruffautlisticletypewriterfashionaxecoloringbookactivatedcharcoaljeanshortsfarm-to-tablemustacheFashionaxesartorialgatekeepsalviadeepvtofuskateboard+1DSADeepvgentrifysrirachaJOMOscenesterhellofleggingsoccupyartpartyfranzenviraltweesynthironyVapecraftbeer+1gluten-freemeditationCronutshoreditchglossiersemioticsnarwhalporkbellylisticleenamelpinmanbunlocavorewhatevermicrodosingceliachealthgothwolfSingle-origincoffeepickledfranzencredgochujangheirloomDIYchillwavebanhmiflannelvinylcoppermugJOMOTry-hardforagevapekinfolkughgodardpokemustachelomovicevegantrustfundroofpartyPutabirdonitbrunchascotswagtry-hardgodardXOXOskateboardcronutYrbeforetheysoldoutsynthgatekeepedisonbulbfingerstacheumamiMumblecorebodegaboyscloudbreadletterpressmessengerbagdrinkingvinegargatekeepmarfahellofvexillologistyesplzcredShabbychicphotoboothvenmoumamiswagpabsthealthgothhellofjeanshortsmigashotchickenRawdenimsrirachashabbychicauthenticprismcraftbeeryouprobablyhaventheardofthemtattooeddirecttradesemioticsPoutinepraxisumami90stonxunicornmukbangviceVicemlkshkroofpartyfoodtruckviralfreeganmicrodosingVHSauthenticmehgatekeepmicrodosingpost-ironicBrooklynCredsrirachastreetartaffogatoshabbychicwolffitDSAvenmoDSAmehsubwaytileaustinfannypackVHSchicharronesknausgaardcloudbreadgastropubBiodieselsmallbatchicelandkitschbeforetheysoldoutbanhmiputabirdonitgluten-freehumblebraghotchickenethicalgodardOrganicmarfasrirachaviraldisruptcoppermugetsynormcoreheirloomWaistcoathumblebragkitschorganicflannelfarm-to-tablemeggingsmeditationstumptownFlannelwilliamsburgnextlevelmumblecorekickstarterlomojianbingpickledquinoaPBR&BXOXOaustinvenmoscenesterSnackwave+1VHStumblrDIYhoodiepour-overPBR&BfingerstachehammockgodardWolfchicharronesintelligentsiavenmoairplantShamancornholeoccupymessengerbaglomohoodiefashionaxeDirecttradeactivatedcharcoalumamibittersairplanthoodietruffautbiodieselchillwavesalviaAffogatovenmohellofkinfolkhumblebrag90sfampop-upceliacBiodieselaffogatobrunchvibecessionshabbychichoodieartpartyPinterestfannypackpokpokascotportlandbiodieselManbunhealthgothsemioticskalechipsSalviahumblebragetsy90sclichevibecessionsnackwave3wolfmoonunicornthundercatshumblebragsnackwavegentrifyVegancold-pressedBrooklynmustachechiaauthenticmeggingsgastropubcrucifixpost-ironicOrganiccredpost-ironicbiodieselTypewritervenmoschlitzcrucifixMastercleansemeggingsmarfacardiganorganicbeardSemioticsstumptownneutraselvage+1JOMOhotchickenhelveticacredtbhkombuchapugwilliamsburgsrirachaYOLOclichevicethundercatssquidcoloringbookironyTweeasymmetricalkitschtacosennuiPolaroidXOXOreadymadenormcoreyrlyftcoppermugmastercleanseRoofpartyunicornXOXOdreamcatcherkogilomobicyclerightsheirloomScenesterdisruptchartreuseunicorngodardviceflexitarianmicrodosingXOXOlyftmixtapeadaptogenafWolfheirloomglossiertumericmanbunbushwicksusbanjoknausgaardretroumamilocavoreorganicLetterpresstumblrdrinkingvinegarbicyclerightsactivatedcharcoalyesplzbrunchtaiyakidreamcatcherLyftVHSmastercleansestreetartpokpoketsyDSAgochujangsquidShoreditchmanbraidsucculentsiPhonecraftbeermessengerbagchambraykickstarterblogWilliamsburgkombuchaknausgaardhealthgothmarfahashtagbluebottlegodardhellofwolfporkbellymumblecorefranzenvinylMarfaironyrawdenimcoppermugsamefranzenstumptownicelandechoparkoffalpickledhoodietrustfundchurch-keyTruffautlyftetsybruhactivatedcharcoalglossiervibecessiontacosauthenticschlitzLumbersexualwokemigasmixtapecraftbeercredbanjorampsvaporwareughManbraidkalechipsblogpour-overcold-pressedfixieswagenamelpintacosbiodieselughdeepvWilliamsburghexagonicelandbicyclerightsactuallyKeffiyehsucculentsjianbingbrunchrampsbloghashtagcoppermugchicharronesYOLOpinteresttry-hardoffalHellatonxgluten-freekitschfixiepabstintelligentsiameditationechoparkkeytarsemioticskalechipsfingerstachemlkshkbespokeChambray3wolfmoon+1synthrawdenimfourdollartoastlive-edgeschlitzeverydaycarryadaptogentweeBanhmisnackwavebushwickjeanshortsselvageSynthsrirachabeardunicornmumblecorevapeprismumamiyouprobablyhaventheardofthemChurch-keyXOXOplaidveganbodegaboysaustinartpartyascottumblrPokpokmumblecoretruffautveganfarm-to-tablekeffiyehretroporkbellymarfaLomopabstafreadymadeveganportlandShoreditchpoutineetsyaffogatotaxidermytousleddisruptsusbitterscoppermugaustinfingerstachesartorialMicrodosingselvagestreetartvibecessionshamankalechipsfingerstachefitcoppermugbanhmipugafJOMOaestheticYouprobablyhaventheardofthemskateboardtweewokesnackwaveKickstarterdrinkingvinegarhumblebragbanhminextlevelslow-carbshoreditchbodegaboysputabirdonitgentrifymumblecoreartpartyjeanshortstildeclicheStumptownadaptogenflanneltonxsamecraymukbangpour-overtumblrWaistcoatumamibiodieselpoutinemukbangcloudbreadsameportlandcraytumerichotchickenfranzensalviaPost-ironicmessengerbagairplantYOLOpour-overVeganfarm-to-tablecraftbeeryuccieYuccieVHShexagonactuallychartreusegreenjuice8-bitgochujangpokpokkogitypewriterchiarawdenimblogPost-ironicbanjopolaroidfreeganlyftseitanbodegaboysListiclehelveticathundercatsartisanauthenticlacroixtruffautmarfaethicalPolaroidfourlokoactivatedcharcoalfoodtruckchiavenmoportlandUmamileggingssquidughsingle-origincoffeestumptownSynthbigmoodtbhvegannextlevelbodegaboysaustinpaleovinylletterpressArtisansynthkitschsmallbatchFannypacktousled+1beardMustacheiPhonedreamcatcherbeforetheysoldoutyrsametaxidermytweeneutrafourlokopokpoktildelive-edgeliterallyactuallyVapetilde+1mehadaptogentry-hardportlandvinylgastropubCold-pressedbruhmanbunhellof90sroofpartyThundercatshammockbeforetheysoldoutgluten-freehelveticayucciepinterestKombuchaseitantruffautethicaldistillerydeepvbanhmicredhealthgothyesplzPugmanbraidbanjoquinoafashionaxekinfolkSameoccupyoffalsnackwaveprismTousledmanbunlocavorevexillologisttumblrsucculentsselfies90siPhonekeytardisruptphotoboothhumblebragHumblebragennui+1flannelvapesingle-origincoffeesartorialfashionaxesalviaoccupyCornholebushwicktweelomogentrifysquidTonxmarfavicelumbersexualpaleobluebottlesucculentsvapeporkbellyclichepraxisswagwhateverkeffiyehbrunchPaleotofuroofpartyvexillologistyrgastropubmukbangmehPolaroidcoloringbookschlitzkinfolkafbluebottleDeepvchurch-keyhumblebragintelligentsiacrayWayfarersknausgaardmixtapepop-upportlandcraftbeerneutrafreeganmehroofpartyBruhflanneltildepolaroidorganicvaporwareCold-pressedwilliamsburghellofwayfarersmustacheskateboardStreetartfoodtruckheirloomtaxidermygentrifypraxissamemeggingsdirecttradebrunchwaistcoatmarfaShamantacosiPhoneroofpartyedisonbulbascotmeditationlive-edgemeh+1mukbangPBR&BpabstfingerstacheVHSSnackwavegastropubennuiyrpoutinetry-hardasymmetricalnextlevelbodegaboysveganethicalvenmotruffautKitschYOLO90svapewilliamsburgBanjodisrupttweeedisonbulbbittersEtsyknausgaardlo-fishamanvaporware90sleggingstonxcardiganbodegaboysIntelligentsiatbhhumblebragmehbluebottlequinoajeanshortssamedirecttradestumptownairplantetsytumblrTildecraftbeershabbychictacosmanbraidtaxidermytry-hardbanhmiwolfvibecessionshamanoccupyironylumbersexualslow-carbPutabirdonittry-hardsubwaytilecold-pressedtonxpalosantomicrodosingschlitzenamelpinroofpartyselfiesgastropubedisonbulbPokechambrayceliaccloudbreadlyftpoutinepugvexillologistbruhDIYMlkshkseitanactivatedcharcoalbluebottlethundercatshotchickenbeardTonxmeditationgluten-freebanhmimanbraidtypewriterfoodtrucktaiyakiphotoboothfarm-to-tableActuallyselfiesmixtapehellofSynthdeepvyouprobablyhaventheardofthemsubwaytilekitschswagviralkogipitchforkputabirdonitVibecessionbeforetheysoldoutfannypackVHSactuallypinterestFourdollartoastsingle-origincoffeechambraygatekeeppugfourlokogastropubpaleoknausgaardmukbangtumblrasymmetrical90skogimeggingsmustachefixieletterpressstumptownLomostumptownslow-carbtonxechoparksuswolf8-bitTumericbeforetheysoldoutheirloommarfahotchickenumamiselfiesairplantgluten-freeRampsaustintousledbanhmiicelandkogibluebottleporkbellyDSAhammocktrustfundseitanfamasymmetricalFitsucculentscraftbeerartisantonxpalosantochambraychillwavenextlevelWayfarersdreamcatchermustacheVHSyrskateboard+1pokehashtagtotebagdeepvtonxYOLOhealthgothFoodtruckheirloomporkbellypitchforkpour-overgastropubascotstreetartflexitariantotebagfamretrotaiyakiBrooklynManbraidcredsemioticsironyFourlokonormcorecredpost-ironicfourdollartoastgodard8-bitlacroix3wolfmoonsynthsmallbatchFourdollartoastfarm-to-tableselvagegluten-freesmallbatchyouprobablyhaventheardofthemtruffautblogfranzenphotoboothChambraycrucifixvenmoartisanStumptowncoloringbookblogreadymadetaxidermybeforetheysoldoutauthenticgreenjuiceglossierPBR&Bchillwavesingle-origincoffeesriracha+1listiclesalviakickstarterartpartyquinoaaffannypackaustinGluten-freeoffal90spugSelfiesauthenticyrascotYOLOrampskeytarbanjounicornorganicveganlive-edgeyouprobablyhaventheardofthemJOMOyuccieTotebagtofuchicharronesbanjotaiyakigochujangcloudbreadpour-overmustacheaffogatotattooedglossierdrinkingvinegarBlogorganicchicharroneslive-edgetonxpickledTattooedcloudbreadchambrayphotoboothsartorialintelligentsiaceliacartpartypabstShoreditchcred90sleggingswhateverbeardsmallbatchtonxkalechipssartorialoffalmicrodosingsquidtumblrPrismportlandhoodiepokpokfithellofvinylroofpartyrawdenimtofupinterestintelligentsiatruffautGatekeepyucciebruhumamipraxiscrucifixrampsnextlevelpour-overaffogatostreetartbeforetheysoldouthashtagkombuchaFlannelXOXOporkbellysquidorganicsusSelfiesplaidechoparkyesplzphotoboothmarfabanhmimessengerbagdirecttradeactivatedcharcoalaffogatosartorialSlow-carbsalviafourdollartoastforagewayfarersliterallycraytrustfunddrinkingvinegarsquidheirloomtypewriterBicyclerightsaftumericdrinkingvinegarshabbychicmukbangcold-pressedhelveticaKitschsartorialtaiyakihumblebragchartreuseprismportlandoffalsalviaKinfolkceliactacosbrunchmanbuncronutgentrifyhashtagkeffiyehPBR&BblogbiodieseladaptogenporkbellyAfhoodietypewritercredsussrirachabushwickmanbraidicelandFranzenschlitzsartorialswagYOLOchartreuseoffalhellapolaroidAsymmetricalshamangatekeepbeardheirloomshabbychichelveticafamlocavorevibecessionmastercleansesustainablepalosantohellofkickstarterIronyDIYhashtagmumblecorewilliamsburglacroixhotchickenretropabsttruffautpaleoporkbellyvexillologistorganicbeforetheysoldoutJianbinglo-fiafgreenjuiceflannelyesplzdirecttradereadymadeprismviralpop-uppolaroidPBR&BchicharroneskitschKalechipsbespokepraxiswhateverhotchickentweeForagetbhairplantbeardpalosantochillwavestumptownXOXOportlandumamismallbatchhelveticavenmoactivatedcharcoalButchercornholevicehashtagpugkitschArtpartybicyclerightsletterpressclichegreenjuicestumptowngentrifymumblecoreviralfannypackPBR&BroofpartyCardiganveganbanjonarwhalportlandsucculentsfarm-to-tabletacosActuallyicelanddirecttradeartisanbeardstumptownyesplzmustachepickledCardigansquidbiodieselascotgentrifykombuchayuccieleggingssusmustachePaleofranzenenamelpinlive-edgeDisruptkombuchasynthlacroixwokewhateverprismughpost-ironicmeditationmeggingsroofpartyPlaidskateboardreadymadeactivatedcharcoalswagdirecttrademixtapeyrchicharroneskinfolkcoloringbookfamvexillologistpolaroidseitanRawdenimpugbanjoquinoaPickledironyintelligentsiapokefourdollartoastpaleofammehFashionaxemastercleansecraygreenjuicelyftbluebottleprismvaporwaremigashellaArtisanoccupysemioticsquinoanextlevelcronutthundercatslumbersexualDistilleryVHSpop-upjeanshortsflannelfashionaxehammockpraxistacosskateboardsamebiodieselTbhyesplzfarm-to-tablequinoaechoparksubwaytilepop-uppugclicheTrustfundlive-edgefoodtruckrawdenimshamancrayviceethicalshoreditchtildeputabirdonityucciejianbingPokeliterallymixtapetattooedbutchercoppermugquinoasquidsynthmlkshkreadymadepraxisnextlevelneutrahammockPolaroidmicrodosingracletteDSAtypewriterheirloomfamcrayvexillologistunicornadaptogenSelvagemumblecorebiodieselfarm-to-tableintelligentsiabeforetheysoldoutwokegatekeepMastercleansetildegatekeep90spoutine3wolfmoonjeanshortsfingerstachecold-pressedporkbellyBitterslacroixlumbersexuallisticlebicyclerightskalechipstbhmarfamukbangflexitarianbiodieseltotebagtypewritercraftbeerCredXOXOhumblebragYOLOphotoboothactuallyyouprobablyhaventheardofthemCornholefoodtruckactivatedcharcoalmumblecoregatekeepdreamcatcherhammockcold-pressedchartreuseFashionaxehumblebragvegancrucifixpaleowaistcoatgastropubprismAfennuichiadrinkingvinegarfixietumericflannelTry-hardjianbingfranzensalviabanjoAustinforagebluebottleblogvinylBigmoodthundercatsyesplzauthenticfitphotoboothYOLOartisanDirecttradethundercatsbanhmibeardfourdollartoastTypewriterPBR&BedisonbulbtweeflanneldisruptaustincardiganfixiegastropubtousledactivatedcharcoaloccupysusascotTonxtumblrgluten-freebanhmifourlokohumblebragmanbraidtaiyakisartorialpugliterallysusphotoboothfoodtruckGluten-freemarfaroofpartycronuttrustfundretropinteresticelandoccupyportlandpost-ironicsynthflexitarianafsameBodegaboysseitanpaleobespokeasymmetricalmessengerbagkogiyouprobablyhaventheardofthemporkbellyjianbingughPortlandfreeganbanjoartisanhotchickenmigasascotnarwhalSustainablefoodtruckumamipitchforkdistillerydrinkingvinegaroffalPolaroidlisticlemukbangpop-upXOXOSingle-origincoffeegodardvapepour-overtattooedbutchertypewriter8-bitironyskateboardveganleggingstaxidermytumericthundercatscloudbreadenamelpinbanhmiflanneltrustfundsamevenmoJianbingshabbychickickstartertousledhumblebragfamethicalwhatevervegantattooedBrooklynicelandPBR&BascotPalosantosartorialorganicechoparkvaporwarechicharronesfreeganedisonbulbTrustfundvenmoneutramehActuallyskateboardhexagontousledtry-hardennuicrucifixmastercleansecraftbeerbruhwokepabstprismfoodtruckvaporwareIPhonetrustfundshabbychicauthenticaffogato3wolfmoonviralblogmarfakalechipsartisangluten-freeschlitzvapehoodiePBR&BtaiyakilomooffalsucculentsLacroixchicharronescloudbreadmehtrustfundtry-hardsusheirloomfashionaxeBitterstumblrbutcherquinoalumbersexualmustachecoppermugDreamcatchermarfafourdollartoastwolfphotoboothcronutwhateverGastropubcrucifixpraxisstreetartPrismportlandnarwhaldrinkingvinegartbhgreenjuiceLiterallylocavorepokpokmehLumbersexualroofpartybruhlomostumptowntumblrironymixtapechillwavefourlokotonxgreenjuicevenmoChillwaveDSAedisonbulbhumblebragbeforetheysoldoutNarwhalDIYtaxidermydrinkingvinegarpop-uptattooednormcorehammockcornholechartreuseraclettetousledviceLocavorebruhletterpresscoppermugKeffiyehdirecttradecrucifixairplantplaidpitchforkracletteadaptogensamedistillerylo-fimumblecoreauthenticdreamcatcherSnackwaveYOLOcronutbodegaboysKinfolkvicescenesterseitanwokedreamcatcherDIYgatekeepChurch-keypraxissingle-origincoffeeknausgaardhotchickentaiyakipoutineNarwhalyuccieblogcold-pressedjeanshortsneutraKeffiyehbicyclerightsechoparktypewriterdirecttrademigaslisticlechartreusemehbigmoodbushwickseitanKickstarterpitchforkbrunchtruffauttaxidermyXOXOcold-pressedgreenjuiceoccupyTruffautpinterestpugsrirachaJOMOmixtapeBushwicksyntheverydaycarryfixiepickledaustinflexitarianyesplzrampsliterallyButcherDIYyrkalechipsbluebottlecraftbeerunicornmigasplaidDirecttradesubwaytilejeanshortsphotoboothpugcoppermugpaleoeverydaycarryPBR&BkeytarhotchickenHeirloomstreetarttumericlyftgreenjuiceafVHSbruhkeytarfashionaxebutcherFreeganDSAbitterslyftfourlokobanjofoodtruckKeffiyehclichelocavoreenamelpinmumblecorecold-pressedgentrifytumblretsyseitanbeforetheysoldouthumblebrag+1skateboardDeepvcronutVHSviralactuallyforagefamfreeganpost-ironichashtagauthenticSrirachachambraylive-edgetruffautbodegaboysnarwhalmixtapesingle-origincoffeeintelligentsiavinylDIYgatekeepYouprobablyhaventheardofthemfourlokokeffiyehseitandistilleryaestheticbigmoodfamkogiFourlokohammockbespokelisticlewolfkickstarterneutraBespokemanbunchiatbhdrinkingvinegarDIYsmallbatchhammockphotoboothtonxSmallbatchleggingscraybigmoodPBR&Bpost-ironicmehmukbangicelandcoloringbookprismglossiermanbunshabbychicYouprobablyhaventheardofthemjianbinglive-edgetofutacosneutratonxtaiyakiglossierkitschYOLOsubwaytiledisruptpaleoPhotoboothlisticleunicornicelandFlannelairplantkalechipssucculentsgreenjuicevapeglossierstumptownpop-upactuallyhotchickenNarwhalcoloringbookasymmetricalbittersmlkshkbespokeneutrabushwickmarfapalosantobodegaboysbicyclerightseverydaycarrysemioticsJianbingslow-carbafbespokemustachequinoafarm-to-tableoccupyhashtag8-bitviralcrayQuinoaforagecloudbreadyouprobablyhaventheardofthemartisanvibecessionbanhmicredpaleoIPhonetypewriterchartreusejianbingbespoketumblrblogtweeskateboardfoodtruckreadymadetaxidermymukbangaustinSkateboardtaiyakikombuchaicelandbutchersubwaytilehelveticaaffogatopraxisascotpitchforkpop-upYrsustainable90sfixiedirecttradebodegaboysgentrifynormcoreliterallyhealthgothcloudbreadporkbellyaesthetictouslededisonbulbLocavoretofujianbingfixiepugicelandEthicaltofufourlokoDIYfitiPhonebicyclerightssynthdistillerytattooedPortlandracletteflexitariankogidistillerytry-hardumamiyuccieartisan90svinylfitDrinkingvinegarhammockbeardBrooklynkogiauthenticfourlokoGatekeepcardiganmlkshkfoodtruckcrucifixdistilleryFourdollartoastveganmeggingsyesplzpinterestwaistcoatviralsnackwavesemioticsSwaghellofpraxiscoppermugstumptowngentrifyvinyltypewriteretsyactuallyReadymadeascotdistillerynarwhalfarm-to-tableasymmetricalughbrunchtbhmanbunfourdollartoasttumblrmustachehotchickenTaiyakiauthenticmeditationYOLOdreamcatcheretsythundercatskalechipsaestheticcronutchillwavetofulacroixchurch-keypugHashtagtruffautsalviajeanshortsmastercleansevenmobruhtotebagletterpressthundercatsoccupyughkalechipsFlexitarianpugcredughTruffautlumbersexualpokeviralpour-overSartorialcardigankalechipsironybicyclerightsBrooklynlisticleletterpressbespokeschlitz+1JOMOrawdenimcornholeDrinkingvinegarbrunchdistillerywokemixtapetacostry-hardyrtaiyakiGlossieradaptogentousledblogbrunch+1lacroixchillwaveNarwhalphotoboothkogitry-hardchiafourdollartoasttofuscenestervexillologistvenmo8-bityuccieportlandneutrabicyclerightsSartorialputabirdonitknausgaardkinfolkgastropubcoloringbookManbraid+1tbhgochujangfreegankalechipsorganicschlitzAirplantmumblecoreknausgaardmanbraidyucciepokpokMeggingsmessengerbagvapefarm-to-tableyuccieknausgaardscenesteroccupymeditationBrooklyntacoschambrayRaclettenormcorechillwaveportlandtaiyakiNarwhaliPhonepraxiscloudbreadphotoboothfarm-to-tabletonxmukbangyucciedreamcatcherEdisonbulbenamelpinwolfsucculentsflannelputabirdonitdreamcatcheraesthetictattooedlo-fimicrodosingslow-carbTotebagcronuthumblebragbittersfashionaxekalechipsflanneledisonbulbicelandmeggingsLive-edgebruhorganicsmallbatchsalviarampskalechipsbushwickpokpokbeardcraftbeerchiatumblrshamantonxVibecessionlumbersexualaustinvexillologistbluebottlepop-up+1mustacheBodegaboystbhafBrooklynkogibushwickstreetarthumblebragPoutinefashionaxesmallbatchletterpressdistilleryeverydaycarrykeytarpour-overgreenjuicemehMastercleanseblogpoutinevaporwareflexitarianlisticlehelveticawaistcoatHashtagcraftbeerbodegaboyswaistcoatraclettepoutineyuccieliterallyflannelvapenextlevelpokepour-overcredtacosAuthentictumblrmicrodosingicelanddrinkingvinegarblogpraxispost-ironicmessengerbagprismvapefannypackwilliamsburgEverydaycarrybutchersartorialwolfDSAVHSgatekeepmessengerbagaffogatoheirloomfourdollartoastethicalhexagonDIYflexitarianhealthgothvibecessionfambiodieselDummytext?Morelikedummythicctextamirite?`;

function trim() {
  let output = dummytext.replace(/ |\.|,/g, '');
  fs.writeFileSync('output.txt', output, { flag: 'a+' });
}

// trim()

function showLength() {
  console.log(dummytext.length);
}

// showLength();

function genUsers(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 40225, (i % 40225) + gap) +
      ' ' +
      dummytext.slice((i % 40225) + gap, (i % 40225) + randomSize() + gap);
    let output = `${text},${randomDate()}\n`;
    fs.writeFileSync('users-seed.csv', output, { flag: 'a+' });
    if (i === 0) {
      console.log('starting users');
    } else if (i % 100000 === 0) {
      console.log(`passing ${i / 1000000} million users`);
    }
  }
  console.log('finished users');
}
function genAlbums(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 40225, (i % 40225) + gap) +
      ' ' +
      dummytext.slice((i % 40225) + gap, (i % 40225) + randomSize() + gap);
    let output = `${text},${randomGenre()},${randomDate()}\n`;
    fs.writeFileSync('albums-seed.csv', output, { flag: 'a+' });
    if (i === 0) {
      console.log('starting albums');
    } else if (i % 100000 === 0) {
      console.log(`passing ${i / 1000000} million albums`);
    }
  }
  console.log('finished albums');
}

function genArtists(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 40225, (i % 40225) + gap) +
      ' ' +
      dummytext.slice((i % 40225) + gap, (i % 40225) + randomSize() + gap);
    let output = `${dummytext.slice(i % 40225, (i % 40225) + randomSize())}\n`;
    fs.writeFileSync('artists-seed.csv', output, { flag: 'a+' });
    if (i === 0) {
      console.log('starting artists');
    } else if (i % 100000 === 0) {
      console.log(`passing ${i / 1000000} million artists`);
    }
  }
  console.log('finished artists');
}

function genPlaylists(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 40225, (i % 40225) + gap) +
      ' ' +
      dummytext.slice((i % 40225) + gap, (i % 40225) + randomSize() + gap);
    let output = `${text},${randomSongCount()}\n`;
    fs.writeFileSync('playlists-seed.csv', output, { flag: 'a+' });
    if (i === 0) {
      console.log('starting playlists');
    } else if (i % 100000 === 0) {
      console.log(`passing ${i / 1000000} million playlists`);
    }
  }
  console.log('finished playlists');
}

function genGenres(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 40225, (i % 40225) + gap) +
      ' ' +
      dummytext.slice((i % 40225) + gap, (i % 40225) + randomSize() + gap);
    let output = `${dummytext.slice(i % 40225, (i % 40225) + randomSize())}\n`;
    fs.writeFileSync('genres-seed.csv', output, { flag: 'a+' });
    if (i === 0) {
      console.log('starting genres');
    } else if (i % 100000 === 0) {
      console.log(`passing ${i / 1000000} million genres`);
    }
  }
  console.log('finished genres');
}

function genSongs(num) {
  for (let i = 0; i < num; i++) {
    let gap = randomSize();
    let text =
      dummytext.slice(i % 40225, (i % 40225) + gap) +
      ' ' +
      dummytext.slice((i % 40225) + gap, (i % 40225) + randomSize() + gap);
    let output = `${text},${randomGenre()},${randomLength()}, ${randomListens()}\n`;
    fs.writeFileSync('songs-seed.csv', output, { flag: 'a+' });
    if (i === 0) {
      console.log('starting songs');
    } else if (i % 100000 === 0) {
      console.log(`passing ${i / 1000000} million songs`);
    }
  }
  console.log('finished songs');
}

// Generate a random song length in seconds from 60s to 360s
function randomLength() {
  return Math.floor(Math.random() * 301 + 60);
}

// Random song count for playlists
function randomSongCount() {
  return Math.floor(Math.random() * 46 + 5);
}

// Generate name length randomly
function randomSize() {
  return Math.floor(Math.random() * 9 + 2);
}

// Generate a random listen count, favors lower numbers thanks to square root
function randomListens() {
  return Math.floor((Math.random() * 10000) ** 2);
}

// Random date after 2012
const start = new Date(2012, 0, 1);
const end = new Date();
function randomDate() {
  let output = new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  return output.toISOString().slice(0, 19).replace('T', ' ');
}

// Brian's randomGenres function
const genres = [
  'Blues',
  'Classical',
  'Country',
  'Electronic',
  'Folk',
  'Hip Hop',
  'Jazz',
  'Latin',
  'Pop',
  'R&B',
  'Rock',
  'Alternative',
  'Indie',
  'Punk',
  'Grunge',
  'Metal',
  'Thrash',
  'Death',
  'Black',
  'Doom',
  'Power',
  'Progressive',
  'Symphonic',
  'Technical',
  'Rap',
  'Trap',
  'Gangsta',
  'Boom Bap',
  'Juke',
  'Footwork',
  'Jungle',
  'Drum and Bass',
  'Breakbeat',
  'Dubstep',
  'Trance',
  'Techno',
  'House',
  'Electro',
  'Disco',
  'Funk',
  'Soul',
  'R&B',
  'Hip Hop',
  'Rap',
  'Gospel',
  'Reggae',
  'Ska',
  'Rocksteady',
  'Dancehall',
  'Dub',
  'World',
  'African',
  'Arabic',
  'Chinese',
  'Indian',
  'Japanese',
  'Korean',
  'Latin',
  'Brazilian',
  'Salsa',
  'Merengue',
  'Cumbia',
  'Reggaeton',
  'Tango',
  'Flamenco',
  'Greek',
  'Irish',
  'Scottish',
  'Welsh',
  'English',
  'American',
  'Bluegrass',
  'Cajun',
  'Creole',
  'Delta Blues',
  'Zydeco',
  'Southern Rock',
  'New Orleans Jazz',
  'Chicago Blues',
  'Tex-Mex',
  'Tejano',
  'Nashville Sound',
  'Honky Tonk',
  'Outlaw Country',
  'Country-Rock',
];
function randomGenre() {
  return genres[Math.floor(Math.random() * genres.length)];
}

const gencount = 100000;

genUsers(gencount);
genAlbums(gencount);
genArtists(gencount);
genGenres(gencount);
genPlaylists(gencount);
genSongs(gencount);

/* ==================== IMPORTANT ==================== */

/*

Step 1: run this file to generate CSVs

Step 2: move all CSVs into 'server-data' within back-end

Step 3: ensure docker is running, then from backend, run :

    npm run docker-db

        -You should now be within docker. 

Step 4: Enter postgres DB

    psql -U postgres

Step 5: Create DB:

    CREATE DATABASE sdc;

Step 6: switch to sdc database

    \c sdc

Step 7: run migration file from within db:

    \i /tmp/server-data/tables-migration.sql

*/
