import { sleep } from 'k6';
import http from 'k6/http';

export const options = {
  ext: {
    loadimpact: {
      distribution: {
        'amazon:us:ashburn': { loadZone: 'amazon:us:ashburn', percent: 50 },
        'amazon:us:columbus': { loadZone: 'amazon:us:columbus', percent: 50 },
      },
      apm: [],
    },
  },
  thresholds: {},
  scenarios: {
    Spike: {
      executor: 'ramping-vus',
      gracefulStop: '30s',
      stages: [
        { target: 5, duration: '30s' },
        { target: 10, duration: '30s' },
        { target: 5, duration: '30s' },
        { target: 0, duration: '30s' },
      ],
      gracefulRampDown: '30s',
      exec: 'spike',
    },
  },
};

const genres = [
  'Blues',
  'Classical',
  'Country',
  'Electronic',
  'Folk',
  'Hip Hop',
  'Jazz',
  'Latin',
  'Pop',
  'R&B',
  'Rock',
  'Alternative',
  'Indie',
  'Punk',
  'Grunge',
  'Metal',
  'Thrash',
  'Death',
  'Black',
  'Doom',
  'Power',
  'Progressive',
  'Symphonic',
  'Technical',
  'Rap',
  'Trap',
  'Gangsta',
  'Boom Bap',
  'Juke',
  'Footwork',
  'Jungle',
  'Drum and Bass',
  'Breakbeat',
  'Dubstep',
  'Trance',
  'Techno',
  'House',
  'Electro',
  'Disco',
  'Funk',
  'Soul',
  'R&B',
  'Hip Hop',
  'Rap',
  'Gospel',
  'Reggae',
  'Ska',
  'Rocksteady',
  'Dancehall',
  'Dub',
  'World',
  'African',
  'Arabic',
  'Chinese',
  'Indian',
  'Japanese',
  'Korean',
  'Latin',
  'Brazilian',
  'Salsa',
  'Merengue',
  'Cumbia',
  'Reggaeton',
  'Tango',
  'Flamenco',
  'Greek',
  'Irish',
  'Scottish',
  'Welsh',
  'English',
  'American',
  'Bluegrass',
  'Cajun',
  'Creole',
  'Delta Blues',
  'Zydeco',
  'Southern Rock',
  'New Orleans Jazz',
  'Chicago Blues',
  'Tex-Mex',
  'Tejano',
  'Nashville Sound',
  'Honky Tonk',
  'Outlaw Country',
  'Country-Rock',
];

const terms = [
  'Ursula',
  'Agustin',
  'Isabella',
  'Tate',
  'Earnest',
  'Angelo',
  'Ova',
  'Giovani',
  'Luther',
  'Deondre',
  'Modesto',
  'Andreanne',
  'Macey',
  'Kendra',
  'Michale',
  'Dominic',
  'Rowena',
  'Kaycee',
  'Sarina',
  'Melissa',
];

const songs = [
  'Because I Love You',
  'Cry Like a Baby',
  'We Can Work it Out',
  'I Will Survive',
  'Sh-Boom',
  'Fence Me In',
  'Sweet Child O',
  'Let Me Call You Sweetheart',
  'Roses Are Red',
  'Pop Muzik',
  'In the Summertime',
  'Auf Wiederseh',
  'Wipe Out',
  'Apologize',
  'April Showers',
  'Magic',
  'Black Velvet',
  'Dancing Queen',
  'Whispering',
];

export function spike() {
  let response;
  for (let i = 0; i < 10; i++) {
    let genre = genres[Math.floor(Math.random() * genres.length)];
    let term = terms[Math.floor(Math.random() * terms.length)];
    let song = songs[Math.floor(Math.random() * songs.length)];
    let count = Math.ceil(Math.random() * 50);
    let id = Math.ceil(Math.random() * 1000000);
    let URLs = [
      `http://localhost:8000/users/name/${term}/${count}`,
      `http://localhost:8000/users/newest/${count}`,
      `http://localhost:8000/users/id/${id}`,
      `http://localhost:8000/artists/name/${term}/${count}`,
      `http://localhost:8000/artist/id/${id}`,
      `http://localhost:8000/albums/name/${song}/${count}`,
      `http://localhost:8000/ablums/newest/${count}`,
      `http://localhost:8000/albums/genre/${genre}`,
      `http://localhost:8000/albums/id/${id}`,
      `http://localhost:8000/songs/name/${song}/${count}`,
      `http://localhost:8000/songs/popular/${count}`,
      `http://localhost:8000/songs/genre/${genre}`,
      `http://localhost:8000/songs/id/${id}`,
      `http://localhost:8000/genres/name/${genre}`,
      `http://localhost:8000/genres/id/${id}`,
      `http://localhost:8000/playlists/user/${id}`,
      `http://localhost:8000/playlists/id/${id}`,
    ];
    response = http.get(URLs[Math.floor(Math.random() * URLs.length)]);
    sleep(1);
  }
}
